# Generated by Django 3.0 on 2025-07-10 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='资源编号')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '多媒体资源',
                'verbose_name_plural': '多媒体资源',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SubPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='页面名称')),
                ('page_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='页面代码(唯一)')),
                ('add_to_index', models.BooleanField(default=False, verbose_name='添加到首页')),
                ('seq', models.IntegerField(default=0, verbose_name='排序号')),
                ('share_desc', models.CharField(max_length=200, null=True, verbose_name='分享描述')),
                ('share_image', models.ImageField(null=True, upload_to='images/mall/share', validators=[django.core.validators.validate_image_file_extension], verbose_name='分享展示图片')),
                ('type', models.SmallIntegerField(choices=[(0, 'APP端'), (1, '小程序端')], default=0, verbose_name='终端类型')),
            ],
            options={
                'verbose_name': '装修页面',
                'verbose_name_plural': '装修页面',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='ResourceImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/mall/res', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('is_dy_show', models.BooleanField(default=True, verbose_name='是否抖音显示')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='renovation.Resource', verbose_name='所属资源')),
            ],
            options={
                'verbose_name': '资源项',
                'verbose_name_plural': '资源项',
                'ordering': ['-pk'],
            },
        ),
    ]
