# Generated by Django 3.0 on 2025-07-11 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenScreenMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/mall/screen', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '首页开屏',
                'verbose_name_plural': '首页开屏',
            },
        ),
    ]
