# Generated by Django 3.0 on 2025-07-14 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0002_openscreenmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='openscreenmedia',
            name='seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位：秒，传视频时必填', verbose_name='视频时间长度(秒)'),
        ),
        migrations.AddField(
            model_name='openscreenmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files/media/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'mpeg', 'mpg'])], verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='openscreenmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/video', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片'),
        ),
    ]
