# Generated by Django 3.0 on 2025-07-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0003_auto_20250714_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('code', models.IntegerField(unique=True, verbose_name='资源编号')),
            ],
            options={
                'verbose_name': '视频资源类型',
                'verbose_name_plural': '视频资源类型',
            },
        ),
        migrations.AlterModelOptions(
            name='openscreenmedia',
            options={'verbose_name': '视频资源', 'verbose_name_plural': '视频资源'},
        ),
        migrations.AddField(
            model_name='openscreenmedia',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='renovation.MediaType', verbose_name='视频资源类型'),
        ),
    ]
