# Generated by Django 3.0 on 2025-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0004_auto_20250716_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='资源编号'),
        ),
    ]
