# Generated by Django 3.0 on 2025-07-10 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统名称')),
                ('official_site_name', models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='官网名称')),
                ('wx_share_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信分享标题')),
                ('wx_share_desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信分享描述')),
                ('wx_share_img', models.ImageField(blank=True, null=True, upload_to='images/mp/basic', validators=[django.core.validators.validate_image_file_extension], verbose_name='微信分享图片')),
                ('venue_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='场馆客服电话')),
                ('custom_work_at', models.CharField(blank=True, max_length=50, null=True, verbose_name='客服服务时间')),
                ('platform_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='平台客服电话')),
                ('maizuo_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='麦座同步失败通知手机')),
                ('tiktok_kf', models.CharField(blank=True, max_length=100, null=True, verbose_name='抖音客服ID')),
                ('service_agreement', models.FileField(blank=True, help_text='只能上传pdf或word', null=True, upload_to='files/basic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='服务协议')),
                ('realname_agreement', models.FileField(blank=True, help_text='只能上传pdf或word', null=True, upload_to='files/basic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='实名须知')),
                ('withdraw_min', models.IntegerField(default=100, verbose_name='最低提现金额')),
                ('auto_cancel_minutes', models.IntegerField(default=5, help_text='订单创建时间开始多少分钟后未支付自动取消订单，解锁位置', validators=[mp.models.auto_cancel_minutes_limit], verbose_name='自动关闭订单分钟数')),
                ('withdraw_fees_ratio', models.IntegerField(default=1, editable=False, help_text='填入5为5%', verbose_name='手续费率')),
                ('business_img', models.ImageField(blank=True, null=True, upload_to='images/mp/basic', validators=[django.core.validators.validate_image_file_extension], verbose_name='商户合作图片')),
                ('goodsindex', models.IntegerField(default=1, editable=False, verbose_name='商品显示配置(技术人员使用)')),
                ('plateindex', models.IntegerField(default=0, editable=False, verbose_name='模块显示配置(技术人员使用)')),
            ],
            options={
                'verbose_name': '商城基本配置',
                'verbose_name_plural': '商城基本配置',
            },
        ),
        migrations.CreateModel(
            name='DouYinPayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('merchant_uid', models.CharField(max_length=32, verbose_name='收款商户号')),
                ('is_default', models.BooleanField(default=False, editable=False, verbose_name='是否默认')),
            ],
            options={
                'verbose_name': '抖音支付配置',
                'verbose_name_plural': '抖音支付配置',
            },
        ),
        migrations.CreateModel(
            name='MaiZuoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
            options={
                'verbose_name': '麦座账户',
                'verbose_name_plural': '麦座账户',
            },
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_short_id', models.CharField(help_text='模板消息的short_id', max_length=64, unique=True, verbose_name='模板编号')),
                ('template_id', models.CharField(help_text='用于发送通知的加密ID，同一模板short_id与公众号(小程序）加密一个ID', max_length=128, verbose_name='模板id')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('template_group', models.CharField(blank=True, help_text='归属同一消息组的不同类型模板，属于面向同一业务场景的模板，比如订单支付成功场景，小程序和公众号可以各有一个模板，但是对应同一个组', max_length=30, null=True, verbose_name='消息组')),
                ('type', models.SmallIntegerField(choices=[(0, '公众号'), (1, '小程序')], default=0, verbose_name='模板类型')),
            ],
            options={
                'verbose_name': '微信模板消息',
                'verbose_name_plural': '微信模板消息',
            },
        ),
        migrations.CreateModel(
            name='ReturnAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='收件人')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=32, null=True, verbose_name='详细地址题')),
            ],
            options={
                'verbose_name': '退货回寄地址设置',
                'verbose_name_plural': '退货回寄地址设置',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bind_day', models.IntegerField(default=30, verbose_name='粉丝解绑天数')),
            ],
            options={
                'verbose_name': '服务配置项',
                'verbose_name_plural': '服务配置项',
            },
        ),
        migrations.CreateModel(
            name='ShareQrcodeBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='尺寸要求: 750 * 1372,必须是这个尺寸,大小不超过800kb', upload_to='images/mall/qr_bk', validators=[mp.models.validate_file_size, django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('enable', models.BooleanField(default=False, verbose_name='生效')),
                ('ver', models.IntegerField(default=6, editable=False)),
            ],
            options={
                'verbose_name': '二维码背景图片',
                'verbose_name_plural': '二维码背景图片',
            },
        ),
        migrations.CreateModel(
            name='SystemDouYin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='来客后台账户名称', max_length=50, null=True, verbose_name='商家名')),
                ('account_id', models.CharField(help_text='来客后台右上角的账户ID', max_length=50, null=True, verbose_name='商户ID')),
                ('client_key', models.CharField(help_text='client_key', max_length=50, verbose_name='应用标识')),
                ('client_secret', models.CharField(help_text='client_secret', max_length=50, verbose_name='应用秘钥')),
            ],
            options={
                'verbose_name': '抖音服务平台',
                'verbose_name_plural': '抖音服务平台',
            },
        ),
        migrations.CreateModel(
            name='SystemDouYinMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(max_length=50, verbose_name='app_secret')),
                ('salt', models.CharField(blank=True, editable=False, help_text='退款用,能力-支付-支付方式管理-支付设置里的SALT', max_length=50, null=True, verbose_name='SALT')),
                ('token', models.CharField(blank=True, editable=False, help_text='退款用,能力-支付-支付方式管理-支付设置里的token', max_length=50, null=True, verbose_name='token')),
            ],
            options={
                'verbose_name': '抖音小程序',
                'verbose_name_plural': '抖音小程序',
            },
        ),
        migrations.CreateModel(
            name='SystemMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '订阅号'), (1, '服务号'), (2, '认证订阅号'), (3, '认证服务号')], default=3, verbose_name='账号类型')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('wx_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(max_length=50, verbose_name='app_secret')),
                ('origin_id', models.CharField(max_length=50, unique=True, verbose_name='原始ID')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('EncodingAESKey', models.CharField(max_length=200, verbose_name='EncodingAESKey')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/wx', validators=[django.core.validators.validate_image_file_extension], verbose_name='公众号头像')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='images/wx', validators=[django.core.validators.validate_image_file_extension], verbose_name='二维码')),
                ('user_head', models.CharField(blank=True, max_length=100, null=True, verbose_name='被邀请人消息标题')),
                ('user_end', models.CharField(blank=True, max_length=100, null=True, verbose_name='被邀请人消息结尾')),
                ('parent_head', models.CharField(blank=True, max_length=100, null=True, verbose_name='推荐人消息标题')),
                ('parent_end', models.CharField(blank=True, max_length=100, null=True, verbose_name='推荐人消息结尾')),
                ('share_img', models.ImageField(blank=True, null=True, upload_to='images/wx', validators=[django.core.validators.validate_image_file_extension], verbose_name='分享背景图')),
            ],
            options={
                'verbose_name': '系统公众号',
                'verbose_name_plural': '系统公众号',
            },
        ),
        migrations.CreateModel(
            name='SystemWxMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(max_length=50, verbose_name='app_secret')),
            ],
            options={
                'verbose_name': '微信小程序',
                'verbose_name_plural': '微信小程序',
            },
        ),
        migrations.CreateModel(
            name='WeiXinPayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('config_type', models.IntegerField(choices=[(3, '小程序支付')], default=1, verbose_name='配置类型')),
                ('is_on', models.BooleanField(default=True, verbose_name='开启')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('app_id', models.CharField(max_length=32, verbose_name='APPID')),
                ('pay_shop_id', models.CharField(max_length=32, verbose_name='微信商户号')),
                ('sub_mch_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='子商户号')),
                ('pay_api_key', models.CharField(max_length=64, verbose_name='微信商户API密钥')),
                ('mch_cert', models.FileField(help_text='请上传文件:apiclient_cert.pem', upload_to='files/wx/wx_cert', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pem'])], verbose_name='商户证书')),
                ('mch_key', models.FileField(help_text='请上传文件:apiclient_key.pem', upload_to='files/wx/wx_cert', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pem'])], verbose_name='商户证书秘钥')),
            ],
            options={
                'verbose_name': '微信支付配置',
                'verbose_name_plural': '微信支付配置',
            },
        ),
        migrations.CreateModel(
            name='DouYinImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.ImageField(upload_to='images/mp/basic', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('basic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.BasicConfig', verbose_name='商城基本配置')),
            ],
            options={
                'verbose_name': '抖音主体证件',
                'verbose_name_plural': '抖音主体证件',
            },
        ),
        migrations.CreateModel(
            name='WxMenu',
            fields=[
            ],
            options={
                'verbose_name': '公众号菜单',
                'verbose_name_plural': '公众号菜单',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mp.returnaddress',),
        ),
    ]
