# Generated by Django 3.0 on 2025-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicconfig',
            name='maizuo_mobile',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='麦座同步失败通知手机'),
        ),
        migrations.AlterField(
            model_name='basicconfig',
            name='tiktok_kf',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='抖音客服ID'),
        ),
    ]
