# Generated by Django 3.0 on 2025-08-19 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_auto_20250730_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicconfig',
            name='agent_agreement',
            field=models.FileField(blank=True, help_text='只能上传pdf或word', null=True, upload_to='files/basic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Ai智能体协议'),
        ),
    ]
