# Generated by Django 3.0 on 2025-09-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_basicconfig_agent_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicconfig',
            options={'verbose_name': '系统基本配置', 'verbose_name_plural': '系统基本配置'},
        ),
    ]
