# Generated by Django 3.0 on 2025-07-10 10:59

from django.db import migrations, models
import django.db.models.deletion
import express.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省')),
                ('province_alias', models.CharField(blank=True, help_text='多个时用井号分割', max_length=100, null=True, verbose_name='省别名')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('county', models.CharField(blank=True, max_length=32, null=True, verbose_name='县')),
                ('type', models.SmallIntegerField(choices=[(0, '省'), (1, '市'), (2, '区(县)')], null=True, verbose_name='级别')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'ordering': ['province', 'city', 'county'],
            },
        ),
        migrations.CreateModel(
            name='ExpressCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='快递公司编码', max_length=30, verbose_name='编码')),
                ('name', models.CharField(help_text='快递公司名称', max_length=50, verbose_name='公司名称')),
                ('display_order', models.IntegerField(default=0, editable=False, help_text='越大越前', verbose_name='排序号')),
            ],
            options={
                'verbose_name': '快递公司',
                'verbose_name_plural': '快递公司',
                'ordering': ('-display_order',),
            },
        ),
        migrations.CreateModel(
            name='GradientChargeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_multiply', models.DecimalField(decimal_places=1, default=0, help_text='该数量以下(含)免邮费, 0代表没有', max_digits=9, verbose_name='免邮数量')),
            ],
            options={
                'verbose_name': '梯度计费配置项',
                'verbose_name_plural': '梯度计费配置项',
            },
            bases=(models.Model, express.models.ItemFee),
        ),
        migrations.CreateModel(
            name='GradientRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.DecimalField(decimal_places=1, default=0, help_text='大于(含)多少', max_digits=9, verbose_name='大于')),
                ('right', models.DecimalField(decimal_places=1, default=0, help_text='小于(不含)多少, 且右值要大于左值', max_digits=9, verbose_name='小于')),
                ('fee', models.DecimalField(decimal_places=1, help_text='邮费金额', max_digits=9, verbose_name='金额')),
            ],
            options={
                'verbose_name': '梯度范围',
                'verbose_name_plural': '梯度范围',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('fee_type', models.IntegerField(choices=[(0, '按量计费')], default=0, editable=False, verbose_name='计费类型')),
                ('exclude_divisions', models.ManyToManyField(blank=True, limit_choices_to=models.Q(type__in=[0, 1]), to='express.Division', verbose_name='不发货区域')),
            ],
            options={
                'verbose_name': '邮费模板',
                'verbose_name_plural': '邮费模板',
            },
            bases=(models.Model, express.models.IFee),
        ),
        migrations.CreateModel(
            name='VolumeChargeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_multiply', models.DecimalField(decimal_places=1, default=0, editable=False, help_text='该数量以下(含)免邮费', max_digits=9, verbose_name='免邮数量')),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='单价')),
                ('divisions', models.ManyToManyField(blank=True, help_text='为空表示默认区域, 即所有没单独设置的区域, 使用此规则', limit_choices_to=models.Q(type__in=[0, 1]), to='express.Division', verbose_name='行政区划')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitems', to='express.Template', verbose_name='按量计费')),
            ],
            options={
                'verbose_name': '城市邮费配置',
                'verbose_name_plural': '城市邮费配置',
            },
        ),
    ]
