# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('express', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属商铺账号'),
        ),
        migrations.AddField(
            model_name='gradientrange',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='express.GradientChargeItem', verbose_name='梯度计费配置项'),
        ),
        migrations.AddField(
            model_name='gradientchargeitem',
            name='divisions',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(type__in=[0, 1]), related_name='gitem', to='express.Division', verbose_name='区域列表'),
        ),
        migrations.AddField(
            model_name='gradientchargeitem',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitems', to='express.Template', verbose_name='梯度计费'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('province', 'city', 'county')},
        ),
    ]
