# Generated by Django 3.0 on 2025-07-10 10:59

import django.core.validators
from django.db import migrations, models
import kuaishou_wxa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KsGoodsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ks_product_id', models.CharField(editable=False, max_length=10, null=True, verbose_name='产品ID')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='原价')),
                ('sold_count', models.IntegerField(default=0, help_text='给快手设置默认销量', verbose_name='销量')),
                ('promotion_commission_rate', models.IntegerField(default=0, help_text='如100表示佣金为万分之一百，即1% 注意：佣金比例＜2800，即佣金比例小于28%', verbose_name='分销佣金比例(万分数)')),
                ('need_push', models.BooleanField(default=True, verbose_name='是否需要推送到快手')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='状态')),
                ('push_status', models.IntegerField(choices=[(1, '待推送'), (4, '已推送'), (2, '审核中'), (3, '审核完成'), (5, '推送失败'), (6, '审核失败')], default=1, verbose_name='快手推送状态')),
                ('fail_msg', models.TextField(blank=True, max_length=1000, null=True, verbose_name='推送错误信息')),
                ('audit_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='快手返回审核id')),
                ('is_lock', models.BooleanField(default=False, editable=False, help_text='锁定期间不允许调用商品对接/编辑接口,到达截止时间自动解锁', verbose_name='是否快手锁定')),
                ('lock_end_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='锁定截止时间')),
                ('lock_reason', models.TextField(blank=True, editable=False, max_length=1000, null=True, verbose_name='锁定的原因')),
                ('push_at', models.DateTimeField(blank=True, null=True, verbose_name='推送时间')),
                ('has_success_push', models.BooleanField(default=False, verbose_name='是否已推送成功')),
            ],
            options={
                'verbose_name': '快手商品配置',
                'verbose_name_plural': '快手商品配置',
            },
        ),
        migrations.CreateModel(
            name='KsGoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.ImageField(help_text='要求长宽比1:1', upload_to='images/ticket/shows/ks', validators=[kuaishou_wxa.models.file_size, django.core.validators.validate_image_file_extension], verbose_name='宣传海报')),
                ('ks_img_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='快手图片img_id')),
            ],
            options={
                'verbose_name': '快手配置',
                'verbose_name_plural': '快手配置',
            },
        ),
        migrations.CreateModel(
            name='KShouLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(help_text='开发资料-开发者ID', max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(help_text='开发资料-开发者ID', max_length=50, verbose_name='app_secret')),
            ],
            options={
                'verbose_name': '快手生活服务平台',
                'verbose_name_plural': '快手生活服务平台',
            },
        ),
        migrations.CreateModel(
            name='KShouPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_app_id', models.CharField(help_text='开发资料-开发者ID', max_length=50, verbose_name='第三方应用appid')),
                ('component_app_secret', models.CharField(help_text='开发资料-开发者ID', max_length=50, null=True, verbose_name='第三方应用secret')),
                ('component_token', models.CharField(max_length=100, verbose_name='消息校检Token')),
                ('component_key', models.CharField(max_length=100, verbose_name='消息加密Key')),
                ('api_url', models.CharField(max_length=50, verbose_name='请求url')),
            ],
            options={
                'verbose_name': '快手小程序第三方平台',
                'verbose_name_plural': '快手小程序第三方平台',
            },
        ),
        migrations.CreateModel(
            name='KShouWxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(max_length=50, null=True, verbose_name='app_secret')),
            ],
            options={
                'verbose_name': '快手授权小程序',
                'verbose_name_plural': '快手授权小程序',
            },
        ),
        migrations.CreateModel(
            name='KsOrderReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, editable=False, max_length=128, verbose_name='订单号')),
                ('status', models.IntegerField(choices=[(1, '待推送'), (4, '已完成')], default=0, verbose_name='状态')),
                ('push_status', models.IntegerField(choices=[(1, '待推送'), (4, '已完成')], default=0, verbose_name='已推送状态')),
                ('ks_settle', models.IntegerField(choices=[(0, '待结算'), (1, '已结算'), (2, '结算失败')], default=0, verbose_name='结算状态')),
                ('error_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='错误信息')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='最新推送时间')),
            ],
            options={
                'verbose_name': '订单同步记录',
                'verbose_name_plural': '订单同步记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='KsOrderSettleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, editable=False, max_length=128, null=True, verbose_name='订单号')),
                ('out_settle_no', models.CharField(db_index=True, default=kuaishou_wxa.models.randomstrwithdatetime_settle, max_length=100, unique=True, verbose_name='结算单号')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='结算描述')),
                ('settle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='申请结算金额')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实际结算金额')),
                ('settle_status', models.CharField(choices=[('DEFAULT', '未结算'), ('SETTLE_PROCESSING', '结算中'), ('SETTLE_SUCCESS', '成功'), ('SETTLE_FAILED', '失败')], default='DEFAULT', max_length=30, verbose_name='状态')),
                ('settle_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='快手结算单号')),
                ('error_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='错误信息')),
                ('create_at', models.DateTimeField(null=True, verbose_name='申请结算时间')),
            ],
            options={
                'verbose_name': '订单结算记录',
                'verbose_name_plural': '订单结算记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='KsPoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='poi名称')),
                ('poi_id', models.CharField(max_length=50, verbose_name='poiid')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('lat', models.FloatField(default=0, verbose_name='纬度')),
                ('lng', models.FloatField(default=0, verbose_name='经度')),
                ('is_merge', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='是否被快手合并')),
                ('new_poi_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='合并后新poiid')),
            ],
            options={
                'verbose_name': '快手poi',
                'verbose_name_plural': '快手poi',
            },
        ),
        migrations.CreateModel(
            name='KsPoiQualityLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='内容')),
                ('val', models.IntegerField(verbose_name='值')),
            ],
            options={
                'verbose_name': 'poi品质标签',
                'verbose_name_plural': 'poi品质标签',
            },
        ),
        migrations.CreateModel(
            name='KsPoiService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.CharField(editable=False, max_length=50, verbose_name='poiid')),
                ('grade_label', models.IntegerField(choices=[(0, '未定义'), (1, '全国连锁店'), (2, '城市连锁店&城市网红店'), (3, '区域店铺')], default=0, editable=False, verbose_name='poi等级标签')),
                ('status', models.CharField(choices=[('DEFAULT', '待审核'), ('APPROVING', '审核中'), ('PASS', '审核通过'), ('REJECT', '审核拒绝'), ('COMBINE', '已作废')], default='DEFAULT', help_text='当被快手合并后，变为作废状态', max_length=10, verbose_name='抖音自动核销状态')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='审核未通过的原因')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'poi挂载记录',
                'verbose_name_plural': 'poi挂载记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='KsShowSecondaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='抖音类目ID', max_length=10, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
            ],
            options={
                'verbose_name': '快手二级类目',
                'verbose_name_plural': '快手二级类目',
            },
        ),
        migrations.CreateModel(
            name='KsShowThirdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='抖音类目ID', max_length=10, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
                ('enable', models.BooleanField(default=True, verbose_name='类目是否开放')),
            ],
            options={
                'verbose_name': '快手三级类目',
                'verbose_name_plural': '快手三级类目',
            },
        ),
        migrations.CreateModel(
            name='KsShowTopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='抖音类目ID', max_length=10, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
            ],
            options={
                'verbose_name': '快手一级类目',
                'verbose_name_plural': '快手一级类目',
            },
        ),
        migrations.CreateModel(
            name='KsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
            ],
            options={
                'verbose_name': '快手店铺',
                'verbose_name_plural': '快手店铺',
            },
        ),
        migrations.CreateModel(
            name='KsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid_ks', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='快手小程序openid')),
                ('session_key', models.CharField(max_length=50, null=True, verbose_name='快手小程序session_key')),
            ],
            options={
                'verbose_name': '快手小程序用户',
                'verbose_name_plural': '快手小程序用户',
            },
        ),
    ]
