# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kuaishou_wxa', '0001_initial'),
        ('express', '0002_auto_20250710_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ksuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ksstore',
            name='city',
            field=models.ForeignKey(limit_choices_to=models.Q(type=1), null=True, on_delete=django.db.models.deletion.SET_NULL, to='express.Division', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='ksstore',
            name='wxa',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuaishou_wxa.KShouWxa', verbose_name='抖音小程序'),
        ),
        migrations.AddField(
            model_name='ksshowthirdcategory',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks_third', to='kuaishou_wxa.KsShowSecondaryCategory', verbose_name='二级分类'),
        ),
        migrations.AddField(
            model_name='ksshowsecondarycategory',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks_secondary', to='kuaishou_wxa.KsShowTopCategory', verbose_name='一级分类'),
        ),
        migrations.AddField(
            model_name='kspoiservice',
            name='kspoi',
            field=models.OneToOneField(help_text='已被合并的不能选择', on_delete=django.db.models.deletion.CASCADE, to='kuaishou_wxa.KsPoi', verbose_name='快手poi'),
        ),
        migrations.AddField(
            model_name='kspoiservice',
            name='quality_labels',
            field=models.ManyToManyField(blank=True, to='kuaishou_wxa.KsPoiQualityLabels', verbose_name='poi品质标签'),
        ),
        migrations.AddField(
            model_name='kspoiservice',
            name='wxa',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuaishou_wxa.KShouWxa', verbose_name='抖音小程序'),
        ),
        migrations.AddField(
            model_name='kspoi',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuaishou_wxa.KsStore', verbose_name='快手店铺'),
        ),
    ]
