# Generated by Django 3.0 on 2025-07-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('kuaishou_wxa', '0002_auto_20250710_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksordersettlerecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketOrder', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ksorderreportrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketOrder', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ksgoodsimage',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ks_show', to='ticket.ShowProject', verbose_name='演出项目'),
        ),
        migrations.AddField(
            model_name='ksgoodsconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuaishou_wxa.KsShowThirdCategory', verbose_name='演出类型'),
        ),
        migrations.AddField(
            model_name='ksgoodsconfig',
            name='poi',
            field=models.ForeignKey(help_text='需选择审核成功的记录，不然推商品和销售会失败', limit_choices_to=models.Q(status='PASS'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuaishou_wxa.KsPoiService', verbose_name='poi'),
        ),
        migrations.AddField(
            model_name='ksgoodsconfig',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ks_session', to='ticket.SessionInfo', verbose_name='场次'),
        ),
    ]
