# Generated by Django 3.0 on 2025-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_wxa', '0003_auto_20250710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksgoodsconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuaishou_wxa.KsShowThirdCategory', verbose_name='节目分类'),
        ),
    ]
