# Generated by Django 3.0 on 2025-07-10 10:59

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, default=common.utils.get_no, max_length=64, null=True, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='减免金额')),
                ('expire_time', models.DateTimeField(verbose_name='使用截止时间')),
                ('user_tips', models.TextField(help_text='提示使用范围等', verbose_name='使用提示')),
                ('status', models.IntegerField(choices=[(2, '上架'), (1, '下架')], default=1, verbose_name='状态')),
                ('off_use', models.BooleanField(default=True, verbose_name='下架后是否可继续使用')),
                ('user_obtain_limit', models.IntegerField(default=0, help_text='0为不限次数', verbose_name='用户限领次数')),
                ('require_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='使用满足金额')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消费券',
                'verbose_name_plural': '消费券',
            },
        ),
        migrations.CreateModel(
            name='UserCouponRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, default=common.utils.get_no, max_length=64, null=True, unique=True, verbose_name='编号')),
                ('status', models.IntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1, verbose_name='状态')),
                ('expire_time', models.DateTimeField(verbose_name='使用截止时间')),
                ('require_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='使用满足金额')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('snapshot', models.TextField(blank=True, editable=False, help_text='领取时保存的快照', null=True, verbose_name='优惠券快照')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '用户优惠券记录',
                'verbose_name_plural': '用户优惠券记录',
            },
        ),
    ]
