# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketOrder', verbose_name='使用订单'),
        ),
        migrations.AddField(
            model_name='usercouponrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_show_types',
            field=models.ManyToManyField(blank=True, related_name='show_types', to='ticket.ShowType', verbose_name='可使用演出类型'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='shows',
            field=models.ManyToManyField(blank=True, related_name='shows', to='ticket.ShowProject', verbose_name='可使用的演出项目'),
        ),
    ]
