# Generated by Django 3.0 on 2025-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20250729_1647'),
        ('coupon', '0002_auto_20250710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='limit_show_types',
            field=models.ManyToManyField(blank=True, related_name='show_types', to='ticket.ShowContentCategorySecond', verbose_name='可使用节目分类'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='shows',
            field=models.ManyToManyField(blank=True, related_name='shows', to='ticket.ShowProject', verbose_name='可使用的节目'),
        ),
    ]
