# Generated by Django 3.0 on 2025-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20250729_1647'),
        ('coupon', '0003_auto_20250729_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='limit_show_types',
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_show_types_second',
            field=models.ManyToManyField(blank=True, related_name='show_types_second', to='ticket.ShowContentCategorySecond', verbose_name='可使用节目分类'),
        ),
    ]
