# Generated by Django 3.0 on 2025-07-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_auto_20250730_1553'),
        ('coupon', '0004_auto_20250729_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercouponrecord',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_order', to='ticket.TicketOrder', verbose_name='使用订单'),
        ),
    ]
