# Generated by Django 3.0 on 2025-08-28 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0005_auto_20250730_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercouponrecord',
            options={'verbose_name': '用户消费券记录', 'verbose_name_plural': '用户消费券记录'},
        ),
        migrations.CreateModel(
            name='UserCouponImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='只支持xlsx', upload_to='files/coupon', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='文件')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注说明')),
                ('status', models.PositiveIntegerField(choices=[(1, '未执行'), (2, '执行中'), (3, '已完成'), (4, '异常')], default=1, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exec_at', models.DateTimeField(blank=True, null=True, verbose_name='执行发放时间')),
                ('total_num', models.IntegerField(default=0, verbose_name='总行数')),
                ('success_num', models.IntegerField(default=0, verbose_name='成功行数')),
                ('fail_num', models.IntegerField(default=0, verbose_name='失败行数')),
                ('fail_msg', models.TextField(blank=True, null=True, verbose_name='失败行信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '批量发放记录',
                'verbose_name_plural': '批量发放记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserCouponCacheRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='发放数量')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon', verbose_name='优惠券')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.UserCouponImport', verbose_name='批量发放记录')),
            ],
            options={
                'verbose_name': '手动发放记录',
                'verbose_name_plural': '手动发放记录',
                'ordering': ['-pk'],
            },
        ),
    ]
