# Generated by Django 3.0 on 2025-08-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20250828_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercouponcacherecord',
            options={'ordering': ['-pk'], 'verbose_name': '未领取记录', 'verbose_name_plural': '未领取记录'},
        ),
    ]
