# Generated by Django 3.0 on 2025-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20250828_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='减免金额'),
        ),
    ]
