# Generated by Django 3.0 on 2025-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0049_auto_20250924_1118'),
        ('coupon', '0008_usercouponrecord_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='80为打8折', verbose_name='打折比率'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='require_num',
            field=models.PositiveSmallIntegerField(default=0, help_text='满张数打折券必填', verbose_name='使用满足张数'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='ticket.SessionInfo', verbose_name='可使用的场次'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满减券'), (2, '满额打折券'), (3, '满张数打折券')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit_show_types_second',
            field=models.ManyToManyField(blank=True, editable=False, related_name='show_types_second', to='ticket.ShowContentCategorySecond', verbose_name='可使用节目分类'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='require_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='满减券、满额打折券必填', max_digits=13, verbose_name='使用满足金额'),
        ),
    ]
