# Generated by Django 3.0 on 2025-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_auto_20250925_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponrecord',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='80为打8折', verbose_name='打折比率'),
        ),
        migrations.AddField(
            model_name='usercouponrecord',
            name='require_num',
            field=models.PositiveSmallIntegerField(default=0, help_text='满张数打折券必填', verbose_name='使用满足张数'),
        ),
        migrations.AlterField(
            model_name='usercouponrecord',
            name='require_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='满减券、满额打折券必填', max_digits=13, verbose_name='使用满足金额'),
        ),
    ]
