# Generated by Django 3.0 on 2025-09-26 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20250926_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/coupon/basic', validators=[django.core.validators.validate_image_file_extension], verbose_name='弹窗图片')),
            ],
            options={
                'verbose_name': '消费券配置',
                'verbose_name_plural': '消费券配置',
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='sessions',
        ),
        migrations.AddField(
            model_name='usercouponrecord',
            name='coupon_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满额减券'), (2, '满额打折券'), (3, '满张数打折券')], default=1, verbose_name='优惠卷类型'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满额减券'), (2, '满额打折券'), (3, '满张数打折券')], default=1, verbose_name='类型'),
        ),
    ]
