# Generated by Django 3.0 on 2025-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_auto_20250926_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='require_num',
            field=models.PositiveSmallIntegerField(default=0, help_text='满张(套)数打折券必填', verbose_name='使用满足张(套)数'),
        ),
    ]
