# Generated by Django 3.0 on 2025-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_auto_20250928_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满额减券'), (2, '满额打折券'), (3, '满张(套)数打折券')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='usercouponrecord',
            name='coupon_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满额减券'), (2, '满额打折券'), (3, '满张(套)数打折券')], default=1, verbose_name='优惠卷类型'),
        ),
    ]
