# Generated by Django 3.0 on 2025-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_auto_20250928_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='消费券价格'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '免费领取'), (2, '付费购买')], default=1, verbose_name='消费券类型'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_buy_limit',
            field=models.IntegerField(default=0, help_text='0为不限次数', verbose_name='限买数量'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '满额减券'), (2, '满额打折券'), (3, '满张(套)数打折券')], default=1, verbose_name='优惠类型'),
        ),
    ]
