# Generated by Django 3.0 on 2025-10-22 15:57

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0014_auto_20251022_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, default=common.utils.get_short_no, max_length=64, null=True, unique=True, verbose_name='编号')),
                ('title', models.CharField(max_length=50, verbose_name='专属活动名称')),
                ('url_link', models.CharField(blank=True, editable=False, help_text='小程序加密URLLink', max_length=100, null=True, verbose_name='领取链接')),
                ('share_img', models.ImageField(upload_to='images/coupon/act', validators=[django.core.validators.validate_image_file_extension], verbose_name='分享图片')),
                ('status', models.PositiveIntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='活动状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('coupons', models.ManyToManyField(to='coupon.Coupon', verbose_name='关联消费券')),
            ],
            options={
                'verbose_name': '用户消费券记录',
                'verbose_name_plural': '用户消费券记录',
                'ordering': ['-pk'],
            },
        ),
    ]
