# Generated by Django 3.0 on 2025-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0015_couponactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponactivity',
            options={'ordering': ['-pk'], 'verbose_name': '专属活动', 'verbose_name_plural': '专属活动'},
        ),
        migrations.AlterField(
            model_name='couponactivity',
            name='title',
            field=models.CharField(max_length=50, verbose_name='活动名称'),
        ),
    ]
