# Generated by Django 3.0 on 2025-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0016_auto_20251023_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user_buy_limit',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user_obtain_limit',
            field=models.IntegerField(default=0, help_text='0为不限次数', verbose_name='用户限领(购)次数'),
        ),
    ]
