# Generated by Django 3.0 on 2025-10-31 17:34

import coupon.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mall.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp', '0004_auto_20250902_1746'),
        ('coupon', '0017_auto_20251023_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_cancel_minutes', models.PositiveSmallIntegerField(default=5, help_text='订单创建时间开始多少分钟后未支付自动取消订单', validators=[coupon.models.coupon_cancel_minutes_limit], verbose_name='自动关闭订单分钟数')),
            ],
            options={
                'verbose_name': '基本配置',
                'verbose_name_plural': '基本配置',
            },
        ),
        migrations.CreateModel(
            name='CouponOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, default=coupon.models.coupon_order_no, max_length=128, unique=True, verbose_name='订单号')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未付款'), (2, '已支付'), (3, '已取消'), (4, '退款中'), (5, '已退款')], default=1, verbose_name='状态')),
                ('multiply', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已退款金额')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易号')),
                ('snapshot', models.TextField(blank=True, editable=False, help_text='下单时保存的快照', max_length=2048, null=True, verbose_name='消费卷快照')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_order', to='coupon.Coupon', verbose_name='消费卷')),
            ],
            options={
                'verbose_name': '购买订单',
                'verbose_name_plural': '购买订单',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CouponReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payno', models.CharField(db_index=True, default=mall.utils.randomstrwithdatetime, max_length=100, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='实付金额')),
                ('status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款')], default=0, verbose_name='状态')),
                ('pay_type', models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型')),
                ('sign', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信支付签名')),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信(抖音)支付单号')),
                ('prepay_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信支付预支付订单号')),
                ('biz', models.SmallIntegerField(choices=[(1, '消费卷订单')], default=1, verbose_name='业务类型')),
                ('attachment', models.TextField(blank=True, help_text='请勿修改此字段', null=True, verbose_name='附加数据')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wx_pay_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付')),
            ],
            options={
                'verbose_name': '消费卷支付记录',
                'verbose_name_plural': '消费卷支付记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CouponOrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '待退款'), (2, '退款支付中'), (3, '退款支付失败'), (4, '已完成'), (5, '已拒绝')], default=1, verbose_name='状态')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='退款金额')),
                ('refund_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='退款原因')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实退金额')),
                ('error_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='退款返回信息')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易号')),
                ('refund_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='退款方退款单号')),
                ('return_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信通信结果')),
                ('result_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信返回结果')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order_no', models.CharField(max_length=128, verbose_name='订单号')),
                ('out_refund_no', models.CharField(db_index=True, default=coupon.models.coupon_refund_no, max_length=64, unique=True, verbose_name='退款单号')),
                ('op_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作退款用户')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_refund', to='coupon.CouponOrder', verbose_name='退款订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消费卷退款记录',
                'verbose_name_plural': '消费卷退款记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='couponorder',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_receipt', to='coupon.CouponReceipt', verbose_name='支付记录'),
        ),
        migrations.AddField(
            model_name='couponorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='couponorder',
            name='wx_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付'),
        ),
    ]
