# Generated by Django 3.0 on 2025-10-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20251031_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponrecord',
            name='buy_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_order', to='coupon.CouponOrder', verbose_name='购买订单'),
        ),
    ]
