# Generated by Django 3.0 on 2025-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_usercouponrecord_buy_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercouponrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期'), (4, '已作废')], default=1, verbose_name='状态'),
        ),
    ]
