# Generated by Django 3.0 on 2025-10-31 18:11

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_auto_20251031_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponConfig',
        ),
        migrations.AddField(
            model_name='couponbasic',
            name='auto_cancel_minutes',
            field=models.PositiveSmallIntegerField(default=5, editable=False, help_text='订单创建时间开始多少分钟后未支付自动取消订单', validators=[coupon.models.coupon_cancel_minutes_limit], verbose_name='自动关闭订单分钟数'),
        ),
    ]
