# Generated by Django 3.0 on 2025-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_auto_20251031_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponorder',
            name='coupon_name',
            field=models.CharField(max_length=128, null=True, verbose_name='消费卷名称'),
        ),
        migrations.AddField(
            model_name='couponorder',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型'),
        ),
    ]
