# Generated by Django 3.0 on 2025-11-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0022_auto_20251107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponorder',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_order', to='coupon.Coupon', verbose_name='消费卷'),
        ),
        migrations.AlterField(
            model_name='couponorder',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_receipt', to='coupon.CouponReceipt', verbose_name='支付记录'),
        ),
        migrations.AlterField(
            model_name='couponorderrefund',
            name='op_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作退款用户'),
        ),
        migrations.AlterField(
            model_name='couponorderrefund',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_refund', to='coupon.CouponOrder', verbose_name='退款订单'),
        ),
        migrations.AlterField(
            model_name='couponorderrefund',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usercouponcacherecord',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon', verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='usercouponimport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AlterField(
            model_name='usercouponrecord',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon', verbose_name='优惠券'),
        ),
    ]
