# Generated by Django 3.0 on 2025-11-19 15:39

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_auto_20251111_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponorder',
            name='pay_end_at',
            field=models.DateTimeField(null=True, verbose_name='支付截止时间'),
        ),
        migrations.AddField(
            model_name='couponorder',
            name='refund_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间'),
        ),
        migrations.AddField(
            model_name='couponreceipt',
            name='pay_end_at',
            field=models.DateTimeField(null=True, verbose_name='支付截止时间'),
        ),
        migrations.AlterField(
            model_name='couponbasic',
            name='auto_cancel_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='订单创建时间开始多少分钟后未支付自动取消订单', validators=[coupon.models.coupon_cancel_minutes_limit], verbose_name='自动关闭订单分钟数'),
        ),
        migrations.AlterField(
            model_name='couponreceipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信支付单号'),
        ),
    ]
