# Generated by Django 3.0 on 2025-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0024_auto_20251119_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponrecord',
            name='win_prize_no',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='中奖序号'),
        ),
    ]
