# Generated by Django 3.0 on 2025-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0025_usercouponrecord_win_prize_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponorder',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额'),
        ),
    ]
