# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mall.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='路径')),
                ('province', models.CharField(blank=True, help_text='省', max_length=20, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, help_text='市', max_length=20, null=True, verbose_name='市')),
                ('county', models.CharField(blank=True, help_text='区/县', max_length=20, null=True, verbose_name='区/县')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='收货地址')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/mall/user/icons', validators=[django.core.validators.validate_image_file_extension], verbose_name='头像')),
                ('openid', models.CharField(blank=True, help_text='微信openid', max_length=50, null=True, unique=True, verbose_name='openid')),
                ('uniacid', models.CharField(blank=True, help_text='公众号id', max_length=20, null=True, verbose_name='公众号id')),
                ('token', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='token')),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=255, null=True, verbose_name='微信头像')),
                ('parent_openid', models.CharField(blank=True, help_text='推荐人openid', max_length=50, null=True, verbose_name='推荐人openid')),
                ('is_wechat_register', models.BooleanField(default=False, verbose_name='是否微信注册')),
                ('is_binding_mobile', models.BooleanField(default=True, verbose_name='是否已绑定')),
                ('share_code', models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='share_code')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='手机')),
                ('idcard', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证')),
                ('wechat', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号')),
                ('follow', models.SmallIntegerField(choices=[(0, '未关注'), (1, '已关注'), (2, '取消关注')], default=0, verbose_name='是否关注')),
                ('flag', models.SmallIntegerField(choices=[(0, '无'), (1, '0.01购票')], default=0, verbose_name='用户权限')),
                ('has_lock_seat', models.BooleanField(default=False, verbose_name='是否有手动出票权限')),
                ('followtime', models.DateTimeField(null=True, verbose_name='关注时间')),
                ('unfollowtime', models.DateTimeField(null=True, verbose_name='取消关注时间')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('last_update_time', models.DateTimeField(blank=True, null=True, verbose_name='上次更新信息时间')),
                ('wx_access_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='微信access_token')),
                ('level', models.IntegerField(default=0, verbose_name='层级')),
                ('has_paid_order', models.BooleanField(default=False, verbose_name='是否有已付款礼包订单')),
                ('qrcode_version', models.IntegerField(default=0, verbose_name='qrcode_version')),
                ('session_key', models.CharField(blank=True, max_length=80, null=True, verbose_name='小程序session_key')),
                ('own_session_key', models.CharField(blank=True, editable=False, max_length=80, null=True, verbose_name='登录session_key')),
                ('unionid', models.CharField(help_text='开放平台unionid', max_length=50, null=True, unique=True, verbose_name='unionid')),
                ('lp_openid', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='小程序openid')),
                ('session_key_tiktok', models.CharField(blank=True, max_length=80, null=True, verbose_name='抖音小程序session_key')),
                ('unionid_tiktok', models.CharField(max_length=50, null=True, unique=True, verbose_name='抖音unionid')),
                ('openid_tiktok', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='抖音小程序openid')),
                ('coordinates', models.CharField(help_text='纬度,经度', max_length=120, null=True, verbose_name='用户默认位置坐标')),
                ('app_openid', models.CharField(blank=True, help_text='App_openid', max_length=50, null=True, verbose_name='app_openid')),
                ('iv', models.IntegerField(default=1, help_text='info的版本号', verbose_name='iv')),
                ('parent_at', models.DateTimeField(blank=True, null=True, verbose_name='绑定上级时间')),
                ('new_parent_at', models.DateTimeField(blank=True, null=True, verbose_name='被推荐时间')),
                ('agree_member', models.BooleanField(default=False, verbose_name='是否已签署用户协议')),
                ('agree_privacy', models.BooleanField(default=False, verbose_name='是否已签署隐私政策')),
                ('has_delete', models.BooleanField(default=False, verbose_name='是否有删除权限')),
                ('has_add', models.BooleanField(default=False, verbose_name='是否有增加权限')),
                ('has_change', models.BooleanField(default=False, verbose_name='是否有修改权限')),
                ('is_tg', models.BooleanField(default=False, verbose_name='是否技术人员账号')),
                ('forbid_order', models.BooleanField(default=False, help_text='勾选后不允许下单', verbose_name='是否禁止下单')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgreementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_member', models.BooleanField(default=False, verbose_name='已签署用户协议')),
                ('agree_privacy', models.BooleanField(default=False, verbose_name='已签署隐私政策')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
            ],
            options={
                'verbose_name': '用户协议隐私记录',
                'verbose_name_plural': '用户协议隐私记录',
            },
        ),
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_at', models.DateField(null=True, verbose_name='到期时间')),
            ],
            options={
                'verbose_name': '用户年度会员卡',
                'verbose_name_plural': '用户年度会员卡',
            },
        ),
        migrations.CreateModel(
            name='HotSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='关键词')),
                ('order_no', models.IntegerField(default=0, help_text='越大越前', verbose_name='排序号')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
                'ordering': ['-order_no'],
            },
        ),
        migrations.CreateModel(
            name='MemberCardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=128, null=True, unique=True, verbose_name='订单号')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='联系电话')),
                ('u_user_id', models.IntegerField(default=0, editable=False, verbose_name='用户id')),
                ('u_agent_id', models.IntegerField(default=0, editable=False, verbose_name='代理id')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款')], default=1, verbose_name='状态')),
                ('source_type', models.IntegerField(choices=[(1, '购买会员卡'), (2, '后台授权')], default=1, verbose_name='授权方式')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
                ('discount', models.DecimalField(decimal_places=1, default=100, max_digits=9, verbose_name='折扣')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('pay_type', models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付'), (8, '抖音小程序支付'), (9, '剧场会员卡余额'), (10, '快手小程序支付'), (11, '小红书小程序支付')], default=-1, verbose_name='支付类型')),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信(抖音)支付单号')),
            ],
            options={
                'verbose_name': '年度会员卡订单',
                'verbose_name_plural': '年度会员卡订单',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='金额')),
                ('days', models.IntegerField(default=0, verbose_name='有效天数')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否开售')),
                ('discount', models.DecimalField(decimal_places=1, default=100, help_text='95表示95折', max_digits=9, verbose_name='折扣')),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='客服电话一')),
                ('customer_mobile_s', models.CharField(blank=True, max_length=20, null=True, verbose_name='客服电话二')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '年度会员卡设置',
                'verbose_name_plural': '年度会员卡设置',
            },
        ),
        migrations.CreateModel(
            name='MembershipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/mall/card', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
            ],
            options={
                'verbose_name': '会员卡详情图',
                'verbose_name_plural': '会员卡详情图',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payno', models.CharField(default=mall.utils.randomstrwithdatetime, max_length=100, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='实付金额')),
                ('status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款')], default=0, verbose_name='状态')),
                ('pay_type', models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付'), (8, '抖音小程序支付'), (9, '剧场会员卡余额'), (10, '快手小程序支付'), (11, '小红书小程序支付')], default=-1, verbose_name='付款类型')),
                ('sign', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信支付签名')),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信(抖音)支付单号')),
                ('prepay_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信支付预支付订单号')),
                ('attachment', models.TextField(blank=True, help_text='请勿修改此字段', null=True, verbose_name='附加数据')),
                ('biz', models.SmallIntegerField(choices=[(1, '票务订单'), (2, '会员卡订单'), (3, '剧场会员卡订单')], default=1, verbose_name='业务类型')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录',
            },
        ),
        migrations.CreateModel(
            name='ServiceAuthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.IntegerField(choices=[(1, '服务协议'), (2, '实名须知')], default=1, verbose_name='协议类型')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
            ],
            options={
                'verbose_name': '用户服务协议记录',
                'verbose_name_plural': '用户服务协议记录',
            },
        ),
        migrations.CreateModel(
            name='TheaterCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='售价')),
                ('receive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='到账余额')),
                ('day_max_num', models.IntegerField(default=4, verbose_name='每日最多购买票数')),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='客服电话一')),
                ('customer_mobile_s', models.CharField(blank=True, max_length=20, null=True, verbose_name='客服电话二')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否启用')),
                ('can_buy', models.BooleanField(default=False, verbose_name='是否售卖')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '剧场会员卡设置',
                'verbose_name_plural': '剧场会员卡设置',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='数额')),
                ('after_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='结算后卡余额')),
                ('source_type', models.IntegerField(choices=[(1, '开通/续费会员卡'), (2, '优惠购票'), (3, '取消订单返还'), (4, '退款返还')], default=1, verbose_name='类型')),
                ('card_order_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='剧场会员卡订单号')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '剧场会员卡余额明细',
                'verbose_name_plural': '剧场会员卡余额明细',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardChangeRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='数额')),
            ],
            options={
                'verbose_name': '剧场会员卡余扣款明细',
                'verbose_name_plural': '剧场会员卡余扣款明细',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=9, verbose_name='优惠折扣')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市优惠',
                'verbose_name_plural': '城市优惠',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/mall/theatercard', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
            ],
            options={
                'verbose_name': '剧场会员卡详情图',
                'verbose_name_plural': '剧场会员卡详情图',
            },
        ),
        migrations.CreateModel(
            name='TheaterCardOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=128, verbose_name='用户剧场会员卡号')),
                ('order_no', models.CharField(default=mall.utils.random_theater_order_no, max_length=128, unique=True, verbose_name='订单号')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('u_user_id', models.IntegerField(default=0, editable=False, verbose_name='用户id')),
                ('u_agent_id', models.IntegerField(default=0, editable=False, verbose_name='代理id')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
                ('receive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='到账余额')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款')], default=1, verbose_name='状态')),
                ('pay_type', models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付'), (8, '抖音小程序支付'), (9, '剧场会员卡余额'), (10, '快手小程序支付'), (11, '小红书小程序支付')], default=-1, verbose_name='支付类型')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信(抖音)支付单号')),
            ],
            options={
                'verbose_name': '剧场会员卡订单',
                'verbose_name_plural': '剧场会员卡订单',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardTicketLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='需和场次创建时的票档描述一致', max_length=20, verbose_name='票档描述')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=9, verbose_name='优惠折扣')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '票档优惠',
                'verbose_name_plural': '票档优惠',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardUserBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('num', models.IntegerField(default=0, verbose_name='购买次数')),
                ('create_at', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户购票统计',
                'verbose_name_plural': '用户购票统计',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(editable=False, null=True, verbose_name='用户ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='余额')),
                ('create_at', models.DateTimeField(null=True, verbose_name='首次充值时间')),
                ('charge_at', models.DateTimeField(null=True, verbose_name='最新充值时间')),
                ('version', models.IntegerField(default=0, editable=False, verbose_name='版本')),
            ],
            options={
                'verbose_name': '剧场会员卡用户记录',
                'verbose_name_plural': '剧场会员卡用户记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.CharField(blank=True, help_text='省', max_length=30, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, help_text='市', max_length=30, null=True, verbose_name='市')),
                ('county', models.CharField(blank=True, help_text='区/县', max_length=30, null=True, verbose_name='区/县')),
                ('street', models.CharField(blank=True, help_text='外部供应链需要,京东天猫', max_length=30, null=True, verbose_name='街道')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('receive_name', models.CharField(max_length=30, verbose_name='收货人姓名')),
                ('default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TheaterCardUserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(default=mall.utils.random_theater_card_no, editable=False, max_length=128, unique=True, verbose_name='卡号')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='余额')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='累计优惠')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_check_bind', models.BooleanField(default=False, verbose_name='是否已首单绑定')),
                ('version', models.IntegerField(default=0, verbose_name='版本')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theater_first_agent', to=settings.AUTH_USER_MODEL, verbose_name='推荐人(代理)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theater_card', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户剧场会员卡',
                'verbose_name_plural': '用户剧场会员卡',
                'ordering': ['-pk'],
            },
        ),
    ]
