# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('express', '0002_auto_20250710_1059'),
        ('ticket', '0001_initial'),
        ('mall', '0001_initial'),
        ('mp', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatercarduserrecord',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Venues', verbose_name='演出场馆（门店）'),
        ),
        migrations.AddField(
            model_name='theatercarduserdetail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCard', verbose_name='剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercarduserdetail',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCardUserRecord', verbose_name='用户剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercarduserbuy',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCardUserRecord', verbose_name='用户剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardticketlevel',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCard', verbose_name='剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardorder',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theater_card_agent', to=settings.AUTH_USER_MODEL, verbose_name='推荐人(代理)'),
        ),
        migrations.AddField(
            model_name='theatercardorder',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCard', verbose_name='剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardorder',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theater_card_receipt', to='mall.Receipt', verbose_name='收款信息'),
        ),
        migrations.AddField(
            model_name='theatercardorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='theatercardorder',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Venues', verbose_name='演出场馆（门店）'),
        ),
        migrations.AddField(
            model_name='theatercardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCard', verbose_name='会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardcity',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCard', verbose_name='剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardcity',
            name='cities',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(type=1), to='express.Division', verbose_name='优惠城市'),
        ),
        migrations.AddField(
            model_name='theatercardchangerecorddetail',
            name='card_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCardUserDetail', verbose_name='剧场会员卡'),
        ),
        migrations.AddField(
            model_name='theatercardchangerecorddetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.TheaterCardChangeRecord', verbose_name='剧场会员卡余额明细'),
        ),
        migrations.AddField(
            model_name='theatercardchangerecord',
            name='ticket_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketOrder', verbose_name='票务订单'),
        ),
        migrations.AddField(
            model_name='theatercardchangerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='theatercard',
            name='wx_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付'),
        ),
        migrations.AddField(
            model_name='serviceauthrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dy_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.DouYinPayConfig', verbose_name='抖音支付商户'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='wx_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付'),
        ),
        migrations.AddField(
            model_name='membershipimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.MembershipCard', verbose_name='会员卡'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='wx_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付'),
        ),
        migrations.AddField(
            model_name='membercardrecord',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_record', to='mall.CardRecord', verbose_name='会员卡记录'),
        ),
        migrations.AddField(
            model_name='membercardrecord',
            name='card_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_agent', to=settings.AUTH_USER_MODEL, verbose_name='推荐人(代理)'),
        ),
        migrations.AddField(
            model_name='membercardrecord',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_receipt', to='mall.Receipt', verbose_name='收款信息'),
        ),
        migrations.AddField(
            model_name='membercardrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='agreementrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最新推荐人'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='上级用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='theatercarduserdetail',
            unique_together={('user_card', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='theatercarduserbuy',
            unique_together={('card', 'create_at')},
        ),
        migrations.AlterUniqueTogether(
            name='theatercardticketlevel',
            unique_together={('card', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='theatercardchangerecorddetail',
            unique_together={('record', 'card_detail')},
        ),
    ]
