# Generated by Django 3.0 on 2025-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20250710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='微信号'),
        ),
    ]
