# Generated by Django 3.0 on 2025-07-28 10:45

from django.db import migrations, models
import mall.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20250724_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payno',
            field=models.CharField(db_index=True, default=mall.utils.randomstrwithdatetime, max_length=100, verbose_name='商户订单号'),
        ),
    ]
