# Generated by Django 3.0 on 2025-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20250728_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementrecord',
            name='agree_agent',
            field=models.BooleanField(default=False, verbose_name='已开启Ai智能体服务'),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_agent',
            field=models.BooleanField(default=False, verbose_name='已开启Ai智能体服务'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agree_member',
            field=models.BooleanField(default=False, verbose_name='已签署用户协议'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agree_privacy',
            field=models.BooleanField(default=False, verbose_name='已签署隐私政策'),
        ),
    ]
