# Generated by Django 3.0 on 2025-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20250819_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='手机'),
        ),
    ]
