# Generated by Django 3.0 on 2025-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20250919_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercardrecord',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型'),
        ),
        migrations.AlterField(
            model_name='theatercardorder',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='支付类型'),
        ),
    ]
