# Generated by Django 3.0 on 2025-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_merge_20251106_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信支付单号'),
        ),
    ]
