# Generated by Django 3.0 on 2025-11-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_auto_20251119_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_visit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='当日登录时间'),
        ),
    ]
