# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XhsPoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='poi名称')),
                ('poi_id', models.CharField(max_length=50, verbose_name='poiid')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('lat', models.FloatField(default=0, verbose_name='纬度')),
                ('lng', models.FloatField(default=0, verbose_name='经度')),
            ],
            options={
                'verbose_name': '小红书poi',
                'verbose_name_plural': '小红书poi',
            },
        ),
        migrations.CreateModel(
            name='XhsShowSecondaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='小红书类目ID', max_length=50, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
            ],
            options={
                'verbose_name': '小红书二级类目',
                'verbose_name_plural': '小红书二级类目',
            },
        ),
        migrations.CreateModel(
            name='XhsShowTopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='小红书类目ID', max_length=50, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
            ],
            options={
                'verbose_name': '小红书一级类目',
                'verbose_name_plural': '小红书一级类目',
            },
        ),
        migrations.CreateModel(
            name='XiaoHongShuWxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('app_secret', models.CharField(max_length=50, null=True, verbose_name='app_secret')),
                ('s_token', models.CharField(max_length=100, verbose_name='消息校检Token')),
                ('encodingAesKey', models.CharField(help_text='encodingAesKey', max_length=100, verbose_name='消息加密Key')),
            ],
            options={
                'verbose_name': '小红书小程序',
                'verbose_name_plural': '小红书小程序',
            },
        ),
        migrations.CreateModel(
            name='XhsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid_xhs', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='openid')),
                ('session_key', models.CharField(max_length=50, null=True, verbose_name='session_key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '小红书小程序用户',
                'verbose_name_plural': '小红书小程序用户',
            },
        ),
        migrations.CreateModel(
            name='XhsShowThirdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='小红书类目ID', max_length=50, null=True, unique=True, verbose_name='类目ID')),
                ('name', models.CharField(max_length=20, verbose_name='类目名称')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_third', to='xiaohongshu.XhsShowSecondaryCategory', verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '小红书三级类目',
                'verbose_name_plural': '小红书三级类目',
            },
        ),
        migrations.AddField(
            model_name='xhsshowsecondarycategory',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_secondary', to='xiaohongshu.XhsShowTopCategory', verbose_name='一级分类'),
        ),
        migrations.CreateModel(
            name='XhsShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=12, verbose_name='短标题')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_show', to='ticket.ShowProject', verbose_name='演出项目')),
            ],
            options={
                'verbose_name': '小红书配置',
                'verbose_name_plural': '小红书配置',
            },
        ),
        migrations.CreateModel(
            name='XhsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, verbose_name='小红书订单id')),
                ('open_id', models.CharField(max_length=100, verbose_name='小红书用户openid')),
                ('pay_snapshot', models.TextField(editable=False, max_length=1000, verbose_name='支付参数')),
                ('item_snapshot', models.TextField(editable=False, verbose_name='下单票档规格')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.SessionInfo', verbose_name='场次')),
                ('ticket_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_order', to='ticket.TicketOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '小红书订单',
                'verbose_name_plural': '小红书订单',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='XhsGoodsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xhs_product_id', models.CharField(editable=False, max_length=10, null=True, verbose_name='产品ID')),
                ('need_push', models.BooleanField(default=True, verbose_name='是否需要推送到小红书')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='状态')),
                ('push_status', models.IntegerField(choices=[(1, '待推送'), (2, '审核中'), (3, '审核完成'), (5, '推送失败'), (6, '审核失败')], default=1, verbose_name='小红书推送状态')),
                ('fail_msg', models.TextField(blank=True, max_length=1000, null=True, verbose_name='推送错误信息')),
                ('push_at', models.DateTimeField(blank=True, null=True, verbose_name='推送时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaohongshu.XhsShowThirdCategory', verbose_name='演出类型')),
                ('poi_list', models.ManyToManyField(to='xiaohongshu.XhsPoi', verbose_name='小红书poi')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_session', to='ticket.SessionInfo', verbose_name='场次')),
            ],
            options={
                'verbose_name': '小红书场次配置',
                'verbose_name_plural': '小红书场次配置',
            },
        ),
        migrations.CreateModel(
            name='XhsVoucherCodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(db_index=True, max_length=100, verbose_name='检票码')),
                ('xhs_check', models.BooleanField(default=False, verbose_name='是否推送核销')),
                ('msg', models.CharField(blank=True, max_length=500, null=True, verbose_name='核销返回')),
                ('ticket_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_code', to='ticket.TicketUserCode', verbose_name='演出票(座位)信息')),
                ('ticket_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '小红书核销码',
                'verbose_name_plural': '小红书核销码',
                'unique_together': {('ticket_code', 'voucher_code')},
            },
        ),
    ]
