# Generated by Django 3.0 on 2025-07-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20250724_1159'),
        ('xiaohongshu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhsshow',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xhs_show', to='ticket.ShowProject', verbose_name='演出节目'),
        ),
    ]
