# Generated by Django 3.0 on 2025-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaohongshu', '0002_auto_20250724_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhsgoodsconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaohongshu.XhsShowThirdCategory', verbose_name='节目分类'),
        ),
    ]
