# Generated by Django 3.0 on 2025-07-10 10:59

from django.db import migrations, models
import django.db.models.deletion
import shopping_points.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=13, verbose_name='金额')),
                ('pay_type', models.IntegerField(choices=[(3, '线下打款')], default=3, verbose_name='支付方式')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approve_at', models.DateTimeField(null=True, verbose_name='提现时间')),
                ('reject_at', models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间')),
                ('status', models.SmallIntegerField(choices=[(0, '提现中'), (1, '已提现'), (2, '已拒绝')], default=0, verbose_name='状态')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=13, verbose_name='提现后余额')),
                ('trade_no', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='交易单号')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='手续费')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '佣金提现记录',
                'verbose_name_plural': '佣金提现记录',
                'ordering': ['-create_at'],
                'abstract': False,
            },
            bases=(models.Model, shopping_points.models.WithdrawActionMixin),
        ),
        migrations.CreateModel(
            name='PointWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.IntegerField(choices=[(3, '线下打款')], default=3, verbose_name='支付方式')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approve_at', models.DateTimeField(null=True, verbose_name='提现时间')),
                ('reject_at', models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=13, verbose_name='提现后余额')),
                ('trade_no', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='交易单号')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='手续费')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=13, verbose_name='积分')),
                ('status', models.SmallIntegerField(choices=[(0, '回购中'), (1, '已回购')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '积分提现',
                'verbose_name_plural': '积分提现',
                'ordering': ['-create_at'],
                'abstract': False,
            },
            bases=(models.Model, shopping_points.models.WithdrawActionMixin),
        ),
        migrations.CreateModel(
            name='ReceiptAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_type', models.IntegerField(choices=[(0, '银行'), (1, '支付宝')], default=0, verbose_name='账户类型')),
                ('account_name', models.CharField(max_length=30, verbose_name='开户人')),
                ('account_no', models.CharField(max_length=50, verbose_name='账户号码')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行名称')),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='银行编号')),
            ],
            options={
                'verbose_name': '用户收款账号',
                'verbose_name_plural': '用户收款账号',
            },
        ),
        migrations.CreateModel(
            name='TransferBalanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=13, verbose_name='金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待确认'), (1, '已确认')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='确认于')),
            ],
            options={
                'verbose_name': '转赠记录',
                'verbose_name_plural': '转赠记录',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='积分余额')),
                ('commission_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='佣金余额')),
                ('total_commission_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总佣金')),
                ('flag', models.SmallIntegerField(choices=[(1, '粉丝'), (2, '验票员'), (3, '代理')], default=1, verbose_name='会员身份')),
                ('manager', models.SmallIntegerField(choices=[(0, '无'), (1, '销售经理')], default=0, verbose_name='改价身份')),
                ('bind_parent_day', models.DateField(blank=True, editable=False, null=True, verbose_name='绑定上级日期')),
                ('version', models.IntegerField(default=0, editable=False, verbose_name='版本')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccountLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('grade', models.IntegerField(help_text='整数, 比如1, 2, 等级顺序从低到高, 越大级别越高', unique=True, verbose_name='Lv')),
                ('slug', models.CharField(help_text='识别序号(请勿修改)', max_length=10, null=True, verbose_name='识别标识')),
                ('share_ratio', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='剧场分销奖比率')),
                ('team_ratio', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='剧场团队奖比率')),
                ('share_ratio_xy', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='巡演分销奖比率')),
                ('team_ratio_xy', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='巡演团队奖比率')),
                ('card_ratio', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='会员卡分销奖比率')),
                ('theater_ratio', models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='剧场会员卡分销比率')),
            ],
            options={
                'verbose_name': '代理等级',
                'verbose_name_plural': '代理等级',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='UserCommissionChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='金额')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('extra_info', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='额外信息')),
                ('source_type', models.IntegerField(choices=[(1, '分销奖'), (2, '团队奖'), (3, '退款扣除'), (4, '会员卡销售'), (5, '剧场会员卡销售')], default=1, verbose_name='类型')),
                ('status', models.IntegerField(choices=[(0, '未结算'), (1, '已结算'), (3, '无效')], default=0, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '佣金明细',
                'verbose_name_plural': '佣金明细',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserPointChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra_info', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='额外信息')),
                ('source_type', models.IntegerField(choices=[(0, '分销奖'), (6, '消费'), (7, '签到赠送'), (8, '返还')], default=0, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='积分')),
                ('status', models.IntegerField(choices=[(3, '未结算'), (1, '已结算'), (2, '无效')], default=3, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='shopping_points.UserAccount', verbose_name='用户账户')),
            ],
            options={
                'verbose_name': '积分明细',
                'verbose_name_plural': '积分明细',
            },
        ),
        migrations.CreateModel(
            name='UserCommissionMonthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未结算'), (1, '已发放'), (3, '无效')], default=0, editable=False, verbose_name='状态')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='金额')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('month', models.PositiveIntegerField(verbose_name='月份')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_points.UserAccount', verbose_name='用户账户')),
            ],
            options={
                'verbose_name': '佣金月度记录',
                'verbose_name_plural': '佣金月度记录',
                'ordering': ['-year', '-month', '-amount'],
            },
        ),
    ]
