# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('shopping_points', '0001_initial'),
        ('mall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommissionmonthrecord',
            name='show_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowType', verbose_name='演出类型'),
        ),
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_account', to='shopping_points.UserAccount', verbose_name='用户账户'),
        ),
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='card_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_order', to='mall.MemberCardRecord', verbose_name='会员卡购买记录'),
        ),
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_order', to='ticket.TicketOrder', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='show_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowType', verbose_name='演出类型'),
        ),
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='theater_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.TheaterCardOrder', verbose_name='剧场会员卡订单'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='inviter',
            field=models.ForeignKey(blank=True, editable=False, help_text='平级邀请时设置，是上级和邀请人的区别', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='shopping_points.UserAccount', verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_points.UserAccountLevel', verbose_name='代理等级'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='promote_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promote_venue', to='ticket.Venues', verbose_name='运营推广门店'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='team_starter_account',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='shopping_points.UserAccount', verbose_name='团队初始人账号'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='venue',
            field=models.ManyToManyField(blank=True, to='ticket.Venues', verbose_name='演出场馆'),
        ),
        migrations.AddField(
            model_name='transferbalancerecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_points.UserAccount', verbose_name='转赠人'),
        ),
        migrations.AddField(
            model_name='transferbalancerecord',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_trans', to='shopping_points.UserAccount', verbose_name='受赠人'),
        ),
        migrations.AddField(
            model_name='receiptaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_accounts', to='shopping_points.UserAccount', verbose_name='用户账户'),
        ),
        migrations.AddField(
            model_name='pointwithdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_points.UserAccount', verbose_name='用户账户'),
        ),
        migrations.AddField(
            model_name='commissionwithdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_points.UserAccount', verbose_name='用户账户'),
        ),
    ]
