# Generated by Django 3.0 on 2025-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20250724_1159'),
        ('shopping_points', '0002_auto_20250710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='venue',
            field=models.ManyToManyField(blank=True, to='ticket.Venues', verbose_name='场馆'),
        ),
    ]
