# Generated by Django 3.0 on 2025-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_points', '0003_auto_20250724_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountlevel',
            name='share_ratio_xy',
        ),
        migrations.RemoveField(
            model_name='useraccountlevel',
            name='team_ratio_xy',
        ),
        migrations.AlterField(
            model_name='useraccountlevel',
            name='share_ratio',
            field=models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='分销奖比率'),
        ),
        migrations.AlterField(
            model_name='useraccountlevel',
            name='team_ratio',
            field=models.DecimalField(decimal_places=1, default=0, help_text='70为70%', max_digits=13, verbose_name='团队奖比率'),
        ),
    ]
