# Generated by Django 3.0 on 2025-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20250730_0958'),
        ('shopping_points', '0004_auto_20250730_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommissionchangerecord',
            name='show_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowType', verbose_name='节目分类'),
        ),
        migrations.AlterField(
            model_name='usercommissionmonthrecord',
            name='show_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowType', verbose_name='节目分类'),
        ),
    ]
