# Generated by Django 3.0 on 2025-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_points', '0005_auto_20250730_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountlevel',
            name='theater_ratio',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, help_text='70为70%', max_digits=13, verbose_name='剧场会员卡分销比率'),
        ),
        migrations.AlterField(
            model_name='usercommissionchangerecord',
            name='source_type',
            field=models.IntegerField(choices=[(1, '分销奖'), (2, '团队奖'), (3, '退款扣除'), (4, '会员卡销售')], default=1, verbose_name='类型'),
        ),
    ]
