# Generated by Django 3.0 on 2025-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_points', '0006_auto_20250730_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommissionchangerecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userpointchangerecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
