# Generated by Django 3.0 on 2025-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_points', '0007_auto_20250822_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountlevel',
            name='card_ratio',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, help_text='70为70%', max_digits=13, verbose_name='会员卡分销奖比率'),
        ),
    ]
