# Generated by Django 3.0 on 2025-09-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_auto_20250822_1413'),
        ('shopping_points', '0008_auto_20250822_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='promote_venue',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promote_venue', to='ticket.Venues', verbose_name='运营推广门店'),
        ),
    ]
