# Generated by Django 3.0 on 2025-11-19 16:17

import blind_box.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindbasic',
            name='auto_cancel_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='订单创建时间开始多少分钟后未支付自动取消订单', validators=[blind_box.models.cancel_minutes_limit], verbose_name='自动取消盲盒订单分钟数'),
        ),
    ]
