# Generated by Django 3.0 on 2025-11-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0002_auto_20251119_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blindboxwinningrecord',
            options={'ordering': ['-pk'], 'verbose_name': '盲盒中奖记录', 'verbose_name_plural': '盲盒中奖记录'},
        ),
    ]
