# Generated by Django 3.0 on 2025-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0003_auto_20251119_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbasic',
            name='box_rule',
            field=models.TextField(max_length=2000, null=True, verbose_name='盲盒规则'),
        ),
        migrations.AddField(
            model_name='blindbasic',
            name='wheel_rule',
            field=models.TextField(max_length=2000, null=True, verbose_name='转盘规则'),
        ),
    ]
