# Generated by Django 3.0 on 2025-11-20 10:51

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0004_auto_20251119_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindbox',
            name='no',
            field=models.CharField(db_index=True, default=common.utils.get_short_no, editable=False, max_length=64, null=True, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='no',
            field=models.CharField(db_index=True, default=common.utils.get_short_no, editable=False, max_length=64, null=True, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='wheelactivity',
            name='no',
            field=models.CharField(db_index=True, default=common.utils.get_short_no, editable=False, max_length=64, null=True, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='wheelsection',
            name='no',
            field=models.CharField(db_index=True, default=common.utils.get_short_no, editable=False, max_length=64, null=True, unique=True, verbose_name='编号'),
        ),
    ]
