# Generated by Django 3.0 on 2025-11-20 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0005_auto_20251120_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelactivity',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='images/wheel', validators=[django.core.validators.validate_image_file_extension], verbose_name='背景图'),
        ),
        migrations.AddField(
            model_name='wheelactivity',
            name='title_image',
            field=models.ImageField(null=True, upload_to='images/wheel', validators=[django.core.validators.validate_image_file_extension], verbose_name='标题图'),
        ),
        migrations.AlterField(
            model_name='wheelactivity',
            name='name',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
    ]
