# Generated by Django 3.0 on 2025-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0006_auto_20251120_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['-display_order'], 'verbose_name': '奖品', 'verbose_name_plural': '奖品'},
        ),
        migrations.AddField(
            model_name='prize',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='越大排越前', verbose_name='排序'),
        ),
    ]
