# Generated by Django 3.0 on 2025-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0007_auto_20251120_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbox',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='越大排越前', verbose_name='排序'),
        ),
    ]
