# Generated by Django 3.0 on 2025-11-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0008_blindbox_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blindbox',
            options={'ordering': ['-display_order', '-pk'], 'verbose_name': '盲盒', 'verbose_name_plural': '盲盒'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['-display_order', '-pk'], 'verbose_name': '奖品', 'verbose_name_plural': '奖品'},
        ),
    ]
