# Generated by Django 3.0 on 2025-11-20 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0009_auto_20251120_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelsection',
            name='thank_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/wheel/section', validators=[django.core.validators.validate_image_file_extension], verbose_name='谢谢参与头图'),
        ),
    ]
