# Generated by Django 3.0 on 2025-11-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0004_auto_20250902_1746'),
        ('blind_box', '0010_wheelsection_thank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxorder',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型'),
        ),
        migrations.AddField(
            model_name='lotterypurchaserecord',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型'),
        ),
        migrations.AddField(
            model_name='lotterypurchaserecord',
            name='wx_pay_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.WeiXinPayConfig', verbose_name='微信支付'),
        ),
    ]
