# Generated by Django 3.0 on 2025-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0011_auto_20251120_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxwinningrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未付款'), (2, '待领取'), (3, '待发货'), (4, '待收货'), (5, '已完成'), (6, '无效')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wheelwinningrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未付款'), (2, '待领取'), (3, '待发货'), (4, '待收货'), (5, '已完成'), (6, '无效')], default=1, verbose_name='状态'),
        ),
    ]
