# Generated by Django 3.0 on 2025-11-20 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0012_auto_20251120_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='head_image',
            field=models.ImageField(null=True, upload_to='images/blind/prize/head', validators=[django.core.validators.validate_image_file_extension], verbose_name='奖品头图'),
        ),
    ]
