# Generated by Django 3.0 on 2025-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0013_auto_20251120_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbasic',
            name='open_buy_times',
            field=models.BooleanField(default=True, verbose_name='是否开启购买转盘次数'),
        ),
    ]
