# Generated by Django 3.0 on 2025-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0014_blindbasic_open_buy_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotterypurchaserecord',
            old_name='purchase_count',
            new_name='multiply',
        ),
        migrations.AddField(
            model_name='lotterypurchaserecord',
            name='pay_end_at',
            field=models.DateTimeField(null=True, verbose_name='支付截止时间'),
        ),
    ]
