# Generated by Django 3.0 on 2025-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0015_auto_20251121_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterypurchaserecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '已付款'), (3, '已取消'), (4, '退款中'), (5, '已退款')], default=1, verbose_name='状态'),
        ),
    ]
