# Generated by Django 3.0 on 2025-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0017_auto_20251121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxorder',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
    ]
