# Generated by Django 3.0 on 2025-11-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0018_blindboxorder_cancel_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLotteryTimesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='次数')),
                ('source_type', models.PositiveSmallIntegerField(choices=[(1, '邀请新用户获得'), (2, '购买获得'), (3, '退款扣减')], default=1, verbose_name='订单类型')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blind_box.UserLotteryTimes', verbose_name='用户转盘次数')),
            ],
            options={
                'verbose_name': '用户转盘次数明细',
                'verbose_name_plural': '用户转盘次数明细',
                'ordering': ['-pk'],
            },
        ),
    ]
