# Generated by Django 3.0 on 2025-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0019_userlotterytimesdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxorder',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额'),
        ),
        migrations.AddField(
            model_name='lotterypurchaserecord',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='blindboxorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='lotterypurchaserecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='金额'),
        ),
    ]
