# Generated by Django 3.0 on 2025-11-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0020_auto_20251124_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlotterytimesdetail',
            name='date_at',
            field=models.DateField(blank=True, editable=False, help_text='用于限制每日登录重复获得', null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='userlotterytimesdetail',
            name='user_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='userlotterytimesdetail',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '邀请新用户获得'), (2, '购买获得'), (3, '退款扣减'), (4, '每日登录赠送')], default=1, verbose_name='订单类型'),
        ),
    ]
