# Generated by Django 3.0 on 2025-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0021_auto_20251125_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlotterytimesdetail',
            name='user_id',
            field=models.IntegerField(db_index=True, editable=False, null=True, verbose_name='用户ID'),
        ),
    ]
