# Generated by Django 3.0 on 2025-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0022_auto_20251125_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlotterytimes',
            name='update_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新时间'),
        ),
    ]
