# Generated by Django 3.0 on 2025-12-05 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0023_auto_20251125_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbox',
            name='award_video',
            field=models.FileField(null=True, upload_to='files/blind/box', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'mpeg', 'mpg'])], verbose_name='开奖动画'),
        ),
        migrations.AddField(
            model_name='blindbox',
            name='back_group_img',
            field=models.ImageField(null=True, upload_to='images/blind/box', validators=[django.core.validators.validate_image_file_extension], verbose_name='盲盒背景图'),
        ),
        migrations.AlterField(
            model_name='blindbox',
            name='grids_num',
            field=models.PositiveSmallIntegerField(choices=[(1, '3格'), (3, '3格'), (6, '6格'), (9, '9格')], default=3, verbose_name='格子数'),
        ),
        migrations.CreateModel(
            name='BlindBoxPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, help_text='用于前端展示,不用于计算，计算以实际权重计算', max_digits=13, verbose_name='中奖概率%')),
                ('is_enabled', models.BooleanField(default=True, help_text='不勾选时不显示该奖品，实际计算概率时不参与计算', verbose_name='是否启用')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='越大排越前', verbose_name='排序')),
                ('blind_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_prizes', to='blind_box.BlindBox', verbose_name='盲盒')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blind_box.Prize', verbose_name='奖品')),
            ],
            options={
                'verbose_name': '盲盒奖品',
                'verbose_name_plural': '盲盒奖品',
                'ordering': ['-display_order'],
            },
        ),
    ]
