# Generated by Django 3.0 on 2025-12-05 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0024_auto_20251205_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindbox',
            name='award_video',
            field=models.FileField(blank=True, null=True, upload_to='files/blind/box', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'mpeg', 'mpg'])], verbose_name='开奖动画'),
        ),
    ]
