# Generated by Django 3.0 on 2025-12-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0025_auto_20251205_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blindboxprize',
            unique_together={('blind_box', 'prize')},
        ),
    ]
