# Generated by Django 3.0 on 2025-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_box', '0026_auto_20251205_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindbox',
            name='grids_num',
            field=models.PositiveSmallIntegerField(choices=[(1, '1格'), (3, '3格'), (6, '6格'), (9, '9格')], default=3, verbose_name='格子数'),
        ),
    ]
