# Generated by Django 3.0 on 2025-07-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mp.systemmp',),
        ),
    ]
