# Generated by Django 3.0 on 2025-07-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('express', '0002_auto_20250710_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStatistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('order_num', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='总实付金额')),
            ],
            options={
                'verbose_name': '每日数据统计',
                'verbose_name_plural': '每日数据统计',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAgentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '代理销售查询',
                'verbose_name_plural': '代理销售查询',
            },
        ),
        migrations.CreateModel(
            name='SessionCpsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '达人销售查询',
                'verbose_name_plural': '达人销售查询',
            },
        ),
        migrations.CreateModel(
            name='TotalStatistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField(default=0, verbose_name='总用户数')),
                ('super_card_num', models.IntegerField(default=0, verbose_name='超级会员数')),
                ('super_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='超级会员卡总收款')),
                ('super_order_num', models.IntegerField(default=0, verbose_name='超级会员卡订单数')),
                ('super_rest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='超级会员卡余额')),
                ('year_card_num', models.IntegerField(default=0, verbose_name='VIP会员数')),
                ('session_num', models.IntegerField(default=0, verbose_name='总场次数')),
                ('dy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='抖音总票房')),
                ('wx_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='微信总票房')),
                ('dy_live_order_num', models.IntegerField(default=0, help_text='下单渠道数量', verbose_name='抖音直播间订单数')),
                ('dy_video_order_num', models.IntegerField(default=0, help_text='下单渠道数量', verbose_name='抖音短视频订单数')),
                ('dy_order_num', models.IntegerField(default=0, help_text='下单渠道数量', verbose_name='抖音小程序订单数')),
                ('wx_order_num', models.IntegerField(default=0, help_text='下单渠道数量', verbose_name='微信小程序订单数')),
                ('refund_num', models.IntegerField(default=0, verbose_name='退款订单总数')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='退款总额')),
                ('agent_num', models.IntegerField(default=0, verbose_name='代理人数')),
                ('withdraw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='已提现佣金')),
                ('total_award_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='总佣金')),
                ('share_award_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='分销奖总数')),
                ('group_award_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='团队奖总数')),
            ],
            options={
                'verbose_name': '总数据统计',
                'verbose_name_plural': '总数据统计',
            },
        ),
        migrations.CreateModel(
            name='SessionSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='场次总佣金')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.SessionInfo', verbose_name='场次')),
            ],
            options={
                'verbose_name': '场次销售统计',
                'verbose_name_plural': '场次销售统计',
            },
        ),
        migrations.CreateModel(
            name='SessionCpsDaySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='达人抖音昵称')),
                ('tiktok_douyinid', models.CharField(blank=True, max_length=50, null=True, verbose_name='达人抖音号')),
                ('source_type', models.IntegerField(choices=[(2, '直播间'), (1, '短视频')], default=2, verbose_name='销售渠道')),
                ('platform', models.IntegerField(choices=[(1, '抖音'), (2, '快手'), (3, '微信视频号')], default=1, verbose_name='平台')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实付金额')),
                ('c_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='佣金')),
                ('create_at', models.DateField(verbose_name='统计日期')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.SessionInfo', verbose_name='场次')),
            ],
            options={
                'verbose_name': '每日达人销售记录',
                'verbose_name_plural': '每日达人销售记录',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAgentSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实付金额')),
                ('c_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='佣金')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='代理')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical.SessionSum', verbose_name='场次销售统计')),
            ],
            options={
                'verbose_name': '代理销售记录',
                'verbose_name_plural': '代理销售记录',
            },
        ),
        migrations.CreateModel(
            name='SessionAgentDaySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.IntegerField(choices=[(4, '微信搜索购买'), (2, '抖音直播间'), (1, '抖音短视频'), (3, '抖音搜索购票')], default=4, verbose_name='销售渠道')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='实付金额')),
                ('c_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='佣金')),
                ('create_at', models.DateField(verbose_name='统计日期')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='代理')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.SessionInfo', verbose_name='场次')),
            ],
            options={
                'verbose_name': '每日代理销售记录',
                'verbose_name_plural': '每日代理销售记录',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('order_num', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='总票房')),
            ],
            options={
                'verbose_name': '月度票房统计',
                'verbose_name_plural': '月度票房统计',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CityStatistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='总实付金额')),
                ('city', models.ForeignKey(limit_choices_to=models.Q(type=1), on_delete=django.db.models.deletion.CASCADE, to='express.Division', verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市数据统计',
                'verbose_name_plural': '城市数据统计',
            },
        ),
    ]
