# Generated by Django 3.0 on 2025-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstatistical',
            name='dy_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13, verbose_name='抖音总票房'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='dy_live_order_num',
            field=models.IntegerField(default=0, editable=False, help_text='下单渠道数量', verbose_name='抖音直播间订单数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='dy_order_num',
            field=models.IntegerField(default=0, editable=False, help_text='下单渠道数量', verbose_name='抖音小程序订单数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='dy_video_order_num',
            field=models.IntegerField(default=0, editable=False, help_text='下单渠道数量', verbose_name='抖音短视频订单数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='super_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13, verbose_name='超级会员卡总收款'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='super_card_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='超级会员数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='super_order_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='超级会员卡订单数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='super_rest_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13, verbose_name='超级会员卡余额'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='wx_order_num',
            field=models.IntegerField(default=0, editable=False, help_text='下单渠道数量', verbose_name='微信小程序订单数'),
        ),
        migrations.AlterField(
            model_name='totalstatistical',
            name='year_card_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='VIP会员数'),
        ),
    ]
