# Generated by Django 3.0 on 2025-10-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0002_auto_20250822_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionsum',
            options={'verbose_name': '场次佣金统计', 'verbose_name_plural': '场次佣金统计'},
        ),
    ]
