# Generated by Django 3.0 on 2025-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaiYiCloudApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('app_id', models.CharField(max_length=50, verbose_name='app_id')),
                ('supplier_id', models.CharField(max_length=64, verbose_name='supplierId')),
                ('private_key', models.TextField(verbose_name='私钥')),
            ],
            options={
                'verbose_name': '彩艺云配置',
                'verbose_name_plural': '彩艺云配置',
            },
        ),
    ]
