# Generated by Django 3.0 on 2025-07-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20250716_1618'),
        ('caiyicloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='节目分类编码')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '节目分类',
                'verbose_name_plural': '节目分类',
            },
        ),
        migrations.CreateModel(
            name='CyGroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, verbose_name='项目组合ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='项目组合名称')),
            ],
            options={
                'verbose_name': '项目组合信息',
                'verbose_name_plural': '项目组合信息',
            },
        ),
        migrations.CreateModel(
            name='CySupplierInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('supplier_id', models.CharField(max_length=100, verbose_name='供应商ID')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='CyShowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='项目ID')),
                ('std_id', models.CharField(max_length=100, verbose_name='中心项目ID')),
                ('seat_type', models.PositiveSmallIntegerField(choices=[(0, '非选座'), (1, '选座')], default=0, verbose_name='项目座位类型')),
                ('ticket_mode', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '票价库存'), (2, '座位库存')], default=0, verbose_name='库存类型')),
                ('poster_url', models.URLField(blank=True, null=True, verbose_name='项目海报地址')),
                ('content_url', models.URLField(blank=True, null=True, verbose_name='项目简介链接')),
                ('category', models.IntegerField(choices=[(1, '演出'), (2, '赛事'), (3, '活动'), (4, '展览')], default=1, verbose_name='节目大类')),
                ('state', models.IntegerField(choices=[(1, '待开售'), (2, '预售中'), (3, '售票中'), (4, '延期'), (5, '取消'), (6, '未开售'), (7, '已结束')], default=1, verbose_name='节目状态')),
                ('expire_order_minute', models.PositiveSmallIntegerField(help_text='单位：分钟', verbose_name='订单支付等待时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CyGroupInfo', verbose_name='项目组合信息')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_show', to='ticket.ShowProject', verbose_name='演出项目')),
                ('supplier_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CySupplierInfo', verbose_name='供应商信息')),
            ],
            options={
                'verbose_name': '节目',
                'verbose_name_plural': '节目',
                'ordering': ['-pk'],
            },
        ),
    ]
