# Generated by Django 3.0 on 2025-07-19 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20250718_0956'),
        ('caiyicloud', '0002_cycategory_cygroupinfo_cyshowevent_cysupplierinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyCheckInMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '入场方式',
                'verbose_name_plural': '入场方式',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CyDeliveryMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '配送方式',
                'verbose_name_plural': '配送方式',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CyIdTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '证件类型',
                'verbose_name_plural': '证件类型',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cy_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='场次ID')),
                ('std_id', models.CharField(max_length=64, verbose_name='中心场次ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='结束时间')),
                ('sale_time', models.DateTimeField(blank=True, null=True, verbose_name='开售时间')),
                ('name', models.CharField(max_length=200, verbose_name='场次名称')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, '未开售'), (2, '待开售'), (3, '预售中'), (4, '售票中'), (5, '结束'), (6, '延期'), (7, '取消')], default=1, verbose_name='场次状态')),
                ('session_type', models.PositiveSmallIntegerField(choices=[(0, '普通场次'), (1, '联票场次')], default=0, verbose_name='场次类型')),
                ('admission_code_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, '联票码'), (1, '基础场次票码')], null=True, verbose_name='入场码类型')),
                ('upload_photo', models.PositiveSmallIntegerField(blank=True, choices=[(0, '无需上传照片'), (1, '需上传照片')], null=True, verbose_name='是否需要上传照片')),
                ('support_no_seat', models.PositiveSmallIntegerField(blank=True, choices=[(0, '不支持非选座购票'), (1, '支持非选座购票')], null=True, verbose_name='是否支持非选座购票')),
                ('require_id_on_ticket', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否需要一票一证购买')),
                ('e_ticket', models.PositiveSmallIntegerField(choices=[(0, '不支持电子票'), (1, '静态码'), (2, '动态码')], default=1, verbose_name='电子票类型')),
                ('paper_ticket', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否支持纸质票出票')),
                ('enable_close_sale_time', models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, verbose_name='是否开启结束售卖时间设置')),
                ('close_sale_time_rule_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '相对时间'), (2, '绝对时间')], null=True, verbose_name='结束售卖时间规则类型')),
                ('close_sale_time', models.DateTimeField(blank=True, null=True, verbose_name='结束售卖时间')),
                ('close_sale_time_interval', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='场次关闭时间间隔(小时)')),
                ('close_sale_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '场次开始前'), (2, '场次结束前'), (3, '场次开始后')], null=True, verbose_name='结束售卖类型')),
                ('limit_on_session', models.PositiveSmallIntegerField(default=6, verbose_name='单场次限购张数')),
                ('limit_on_event', models.PositiveSmallIntegerField(default=20, verbose_name='单节目限购张数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('c_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_session', to='ticket.SessionInfo', verbose_name='演出场次')),
                ('check_in_methods', models.ManyToManyField(blank=True, to='caiyicloud.CyCheckInMethods', verbose_name='入场方式列表')),
                ('delivery_methods', models.ManyToManyField(blank=True, to='caiyicloud.CyDeliveryMethods', verbose_name='配送方式列表')),
            ],
            options={
                'verbose_name': '场次',
                'verbose_name_plural': '场次',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CyTicketPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cy_no', models.CharField(db_index=True, help_text='套票子项id', max_length=64, unique=True)),
                ('ticket_type_id', models.CharField(help_text='票档-票价id', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='基础票价格', max_digits=10)),
                ('qty', models.IntegerField(help_text='数量', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': '套票子项',
                'verbose_name_plural': '套票子项',
            },
        ),
        migrations.CreateModel(
            name='CyTicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cy_no', models.CharField(db_index=True, help_text='票价id', max_length=64, unique=True)),
                ('std_id', models.CharField(help_text='中心票价id', max_length=64)),
                ('name', models.CharField(help_text='票价名称', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='票价，单位：元', max_digits=10)),
                ('comment', models.CharField(blank=True, help_text='票价说明', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='颜色', max_length=20, null=True)),
                ('enabled', models.IntegerField(choices=[(0, '未启用'), (1, '启用')], default=1, help_text='是否启用，1：启用；0：未启用')),
                ('sold_out_state', models.IntegerField(blank=True, choices=[(1, '可售'), (2, '停售')], help_text='是否停售, 1:可售，2:停售', null=True)),
                ('category', models.IntegerField(choices=[(1, '基础票'), (2, '固定套票'), (3, '自由套票')], default=1, help_text='类别，1：基础票，2：固定套票，3:自由套票')),
                ('seq', models.IntegerField(default=1, help_text='票价顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('cy_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CySession', verbose_name='关联节目')),
                ('ticket_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_tf', to='ticket.TicketFile', verbose_name='票档')),
                ('ticket_pack_list', models.ManyToManyField(blank=True, help_text='套票组成信息，基础票为空', to='caiyicloud.CyTicketPack')),
            ],
            options={
                'verbose_name': '票档',
                'verbose_name_plural': '票档',
                'ordering': ['seq', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CyVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=32, verbose_name='省')),
                ('city_name', models.CharField(max_length=32, verbose_name='市')),
                ('cy_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='场馆ID')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_venue', to='ticket.Venues', verbose_name='演出场馆')),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
                'ordering': ['-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='cyshowevent',
            name='group_info',
        ),
        migrations.RemoveField(
            model_name='cyshowevent',
            name='supplier_info',
        ),
        migrations.AddField(
            model_name='cyshowevent',
            name='snapshot',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='其他信息'),
        ),
        migrations.AlterField(
            model_name='cycategory',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='cycategory',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '演出'), (2, '赛事'), (3, '活动'), (4, '展览')], default=1, verbose_name='节目大类'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='event_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='项目ID'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, '待开售'), (2, '预售中'), (3, '售票中'), (4, '延期'), (5, '取消'), (6, '未开售'), (7, '已结束')], default=1, verbose_name='节目状态'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='std_id',
            field=models.CharField(max_length=64, verbose_name='中心项目ID'),
        ),
        migrations.DeleteModel(
            name='CyGroupInfo',
        ),
        migrations.DeleteModel(
            name='CySupplierInfo',
        ),
        migrations.AddField(
            model_name='cysession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyShowEvent', verbose_name='关联节目'),
        ),
        migrations.AddField(
            model_name='cysession',
            name='id_types',
            field=models.ManyToManyField(blank=True, to='caiyicloud.CyIdTypes', verbose_name='证件类型列表'),
        ),
    ]
