# Generated by Django 3.0 on 2025-07-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0003_auto_20250719_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyshowevent',
            name='show_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CyCategory', verbose_name='节目分类'),
        ),
    ]
