# Generated by Django 3.0 on 2025-07-19 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0004_cyshowevent_show_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyticketpack',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='基础票价格', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cyticketpack',
            name='qty',
            field=models.IntegerField(default=1, help_text='数量', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
