# Generated by Django 3.0 on 2025-07-19 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0005_auto_20250719_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyticketpack',
            name='cy_no',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='套票子项id'),
        ),
        migrations.AlterField(
            model_name='cyticketpack',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础票价格'),
        ),
        migrations.AlterField(
            model_name='cyticketpack',
            name='qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='cyticketpack',
            name='ticket_type_id',
            field=models.CharField(max_length=50, verbose_name='票档-票价id'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='category',
            field=models.IntegerField(choices=[(1, '基础票'), (2, '固定套票'), (3, '自由套票')], default=1, help_text='1：基础票，2：固定套票，3:自由套票', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='票价说明'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='cy_no',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='票价id'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='enabled',
            field=models.IntegerField(choices=[(0, '未启用'), (1, '启用')], default=1, help_text='1：启用；0：未启用', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='票价名称'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='单位：元', max_digits=10, verbose_name='票价'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='seq',
            field=models.IntegerField(default=1, verbose_name='票价顺序'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='sold_out_state',
            field=models.IntegerField(blank=True, choices=[(1, '可售'), (2, '停售')], help_text=' 1:可售，2:停售', null=True, verbose_name='是否停售'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='std_id',
            field=models.CharField(max_length=64, verbose_name='中心票价id'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='ticket_pack_list',
            field=models.ManyToManyField(blank=True, help_text='基础票为空', to='caiyicloud.CyTicketPack', verbose_name='套票组成信息'),
        ),
        migrations.AlterField(
            model_name='cytickettype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
