# Generated by Django 3.0 on 2025-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0006_auto_20250719_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyticketpack',
            name='ticket_type_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='票档-票价id'),
        ),
    ]
