# Generated by Django 3.0 on 2025-07-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20250724_1159'),
        ('caiyicloud', '0007_auto_20250719_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cy_order_no', models.CharField(db_index=True, max_length=100, verbose_name='彩艺云订单号')),
                ('order_state', models.PositiveSmallIntegerField(choices=[(1, '已下单'), (2, '已支付'), (3, '已出票'), (5, '已完成'), (7, '已关闭'), (8, '已取消')], default=1, verbose_name='订单状态')),
                ('buyer_cellphone', models.CharField(help_text='购票人手机号', max_length=20)),
                ('auto_cancel_order_time', models.DateTimeField(verbose_name='订单未支付自动取消时间')),
                ('exchange_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='换票码')),
                ('exchange_qr_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='换二维票码')),
                ('code_type', models.PositiveSmallIntegerField(choices=[(1, '文本码'), (3, 'URL链接')], default=1, verbose_name='二维码类型')),
                ('ticket_list_snapshot', models.TextField(editable=False, help_text='下单时的ticket_list', verbose_name='下单票档规格')),
                ('need_confirm', models.BooleanField(default=False, verbose_name='是否需要任务确认')),
                ('confirm_times', models.PositiveSmallIntegerField(default=0, verbose_name='确认订单次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='cydeliverymethods',
            options={'ordering': ['code'], 'verbose_name': '配送方式', 'verbose_name_plural': '配送方式'},
        ),
        migrations.AddField(
            model_name='cysession',
            name='require_id_on_order',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否需要一单一证购买'),
        ),
        migrations.AlterField(
            model_name='cysession',
            name='c_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_session', to='ticket.SessionInfo', verbose_name='场次'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_show', to='ticket.ShowProject', verbose_name='节目'),
        ),
        migrations.AlterField(
            model_name='cyvenue',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_venue', to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.CreateModel(
            name='CyTicketCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_type', models.PositiveSmallIntegerField(choices=[(1, '二维码类型'), (3, 'URL链接')], default=1, verbose_name='二维码类型')),
                ('check_in_code', models.CharField(db_index=True, max_length=500, verbose_name='二维码')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '已生效'), (1, '已锁定'), (2, '已退'), (3, '转出中'), (4, '已转出'), (6, '转出票已退票')], default=0, verbose_name='状态')),
                ('check_state', models.PositiveSmallIntegerField(choices=[(0, '未核销'), (1, '已核销'), (2, '部分核销')], default=0, verbose_name='核销状态')),
                ('cy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyOrder', verbose_name='订单')),
                ('ticket_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_code', to='ticket.TicketUserCode', verbose_name='演出票(座位)信息')),
            ],
            options={
                'verbose_name': '小红书核销码',
                'verbose_name_plural': '小红书核销码',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CyOrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(max_length=64, verbose_name='售后申请id')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '审核中'), (2, '审核通过'), (3, '审核失败')], default=1, verbose_name='退款审核状态')),
                ('error_msg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='退款返回信息')),
                ('cy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyOrder', verbose_name='退款订单')),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cy_refund', to='ticket.TicketOrderRefund', verbose_name='退款记录')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='cyorder',
            name='cy_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CySession', verbose_name='彩艺场次'),
        ),
        migrations.AddField(
            model_name='cyorder',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caiyicloud.CyDeliveryMethods', verbose_name='配送方式'),
        ),
        migrations.AddField(
            model_name='cyorder',
            name='ticket_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cy_order', to='ticket.TicketOrder', verbose_name='订单'),
        ),
    ]
