# Generated by Django 3.0 on 2025-07-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0008_auto_20250724_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyFirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '节目大类',
                'verbose_name_plural': '节目大类',
            },
        ),
        migrations.AddField(
            model_name='cycategory',
            name='first_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caiyicloud.CyFirstCategory', verbose_name='节目大类'),
        ),
    ]
