# Generated by Django 3.0 on 2025-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0009_auto_20250728_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytickettype',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='库存数量'),
        ),
    ]
