# Generated by Django 3.0 on 2025-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0010_cytickettype_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='caiyicloudapp',
            name='notify_private_key',
            field=models.TextField(null=True, verbose_name='回调私钥'),
        ),
        migrations.AlterField(
            model_name='caiyicloudapp',
            name='private_key',
            field=models.TextField(verbose_name='api私钥'),
        ),
    ]
