# Generated by Django 3.0 on 2025-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0011_auto_20250730_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytickettype',
            name='origin_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='单位：元', max_digits=10, verbose_name='原价'),
        ),
    ]
