# Generated by Django 3.0 on 2025-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0012_cytickettype_origin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='caiyicloudapp',
            name='notify_public_key',
            field=models.TextField(null=True, verbose_name='回调公钥'),
        ),
    ]
