# Generated by Django 3.0 on 2025-08-02 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0013_caiyicloudapp_notify_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyorder',
            name='exchange_qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/cy_cloud/order', validators=[django.core.validators.validate_image_file_extension], verbose_name='检票二维码'),
        ),
        migrations.AlterField(
            model_name='cyorder',
            name='buyer_cellphone',
            field=models.CharField(max_length=20, verbose_name='购票人手机号'),
        ),
    ]
