# Generated by Django 3.0 on 2025-08-02 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0014_auto_20250802_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyticketcode',
            name='check_in_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/cy_cloud/code', validators=[django.core.validators.validate_image_file_extension], verbose_name='二维码图片'),
        ),
        migrations.AddField(
            model_name='cyticketcode',
            name='snapshot',
            field=models.TextField(editable=False, help_text='彩艺订单的ticket_list', null=True, verbose_name='票信息快照'),
        ),
        migrations.AddField(
            model_name='cyticketcode',
            name='ticket_id',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='票ID'),
        ),
        migrations.AddField(
            model_name='cyticketcode',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='票号'),
        ),
        migrations.AlterField(
            model_name='cyorder',
            name='exchange_qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/cy_cloud/order', validators=[django.core.validators.validate_image_file_extension], verbose_name='换二维票码二维码'),
        ),
        migrations.AlterField(
            model_name='cyticketcode',
            name='check_in_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='二维码'),
        ),
    ]
