# Generated by Django 3.0 on 2025-08-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0015_auto_20250802_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyticketcode',
            options={'ordering': ['-pk'], 'verbose_name': '票信息', 'verbose_name_plural': '票信息'},
        ),
    ]
