# Generated by Django 3.0 on 2025-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0016_auto_20250802_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyorderrefund',
            name='approve_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
