# Generated by Django 3.0 on 2025-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0017_cyorderrefund_approve_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyticketcode',
            name='ac_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
        migrations.AddField(
            model_name='cyticketcode',
            name='check_times',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已核验次数'),
        ),
    ]
