# Generated by Django 3.0 on 2025-08-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0018_auto_20250806_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CySessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caiyicloud.CySession', verbose_name='场次')),
            ],
            options={
                'verbose_name': '场次修改日志',
                'verbose_name_plural': '场次修改日志',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CyEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caiyicloud.CyShowEvent', verbose_name='节目')),
            ],
            options={
                'verbose_name': '项目修改日志',
                'verbose_name_plural': '项目修改日志',
                'ordering': ['-pk'],
            },
        ),
    ]
