# Generated by Django 3.0 on 2025-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0019_cyeventlog_cysessionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyeventlog',
            options={'ordering': ['-pk'], 'verbose_name': '节目修改日志', 'verbose_name_plural': '节目修改日志'},
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='content_url',
            field=models.URLField(blank=True, null=True, verbose_name='节目简介链接'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='event_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='节目ID'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='节目海报地址'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='seat_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '非选座'), (1, '选座')], default=0, verbose_name='节目座位类型'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='std_id',
            field=models.CharField(max_length=64, verbose_name='中心节目ID'),
        ),
    ]
