# Generated by Django 3.0 on 2025-08-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0020_auto_20250808_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyeventlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyShowEvent', verbose_name='节目'),
        ),
        migrations.AlterField(
            model_name='cysessionlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CySession', verbose_name='场次'),
        ),
    ]
