# Generated by Django 3.0 on 2025-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0021_auto_20250821_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyshowevent',
            name='is_delete',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否删除'),
        ),
    ]
