# Generated by Django 3.0 on 2025-09-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0022_cyshowevent_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.CharField(db_index=True, max_length=24, verbose_name='活动ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '满减满折')], verbose_name='营销活动策略')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '满额立减'), (2, '每满立减'), (3, '满件打折'), (4, '满额打折'), (5, '每满件立减'), (6, '满件立减')], verbose_name='营销活动类型')),
                ('enabled', models.PositiveSmallIntegerField(choices=[(1, '启用'), (0, '未启用')], verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('display_name', models.BooleanField(default=False, verbose_name='是否显示名称')),
                ('cross_product', models.BooleanField(default=False, verbose_name='允许跨项目/场次')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('rule', models.TextField(blank=True, null=True, verbose_name='活动规则')),
            ],
            options={
                'verbose_name': '营销活动',
                'verbose_name_plural': '营销活动',
            },
        ),
        migrations.CreateModel(
            name='PromoteRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='满足件数')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='满足金额')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='打折金额/费率，金额时，单位分；费率时，打九折为10', max_digits=10, null=True, verbose_name='打折金额/费率')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='caiyicloud.PromoteActivity')),
            ],
            options={
                'verbose_name': '活动规则',
                'verbose_name_plural': '活动规则',
            },
        ),
        migrations.CreateModel(
            name='PromoteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_session', models.BooleanField(default=False, verbose_name='是否必须')),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(1, '节目'), (2, '场次/票价')], default=1, verbose_name='适用方式')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='caiyicloud.PromoteActivity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyShowEvent', verbose_name='节目')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CySession', verbose_name='场次')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caiyicloud.CyTicketType', verbose_name='票档')),
            ],
            options={
                'verbose_name': '活动应用范围',
                'verbose_name_plural': '活动应用范围',
            },
        ),
    ]
