# Generated by Django 3.0 on 2025-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0023_promoteactivity_promoteproduct_promoterule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoteactivity',
            name='enabled',
            field=models.PositiveSmallIntegerField(choices=[(2, '已结束'), (1, '启用'), (0, '未启用')], verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='promoteactivity',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='promoteactivity',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间'),
        ),
    ]
