# Generated by Django 3.0 on 2025-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0024_auto_20250901_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterule',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='满足金额(分)'),
        ),
        migrations.AlterField(
            model_name='promoterule',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='打折金额/费率，金额时，单位分；费率时，打九折为10', max_digits=10, null=True, verbose_name='打折金额(分)/费率(九折为10)'),
        ),
    ]
