# Generated by Django 3.0 on 2025-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0025_auto_20250902_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyshowevent',
            name='error_msg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='拉取错误信息'),
        ),
    ]
