# Generated by Django 3.0 on 2025-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0026_cyshowevent_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyticketcode',
            name='check_in_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '二维码类型'), (3, 'URL链接')], default=1, verbose_name='二维码类型'),
        ),
    ]
