# Generated by Django 3.0 on 2025-11-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0052_auto_20251110_1127'),
        ('caiyicloud', '0027_auto_20250915_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyorder',
            name='cy_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CySession', verbose_name='彩艺场次'),
        ),
        migrations.AlterField(
            model_name='cyorder',
            name='ticket_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_order', to='ticket.TicketOrder', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='cysession',
            name='c_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_session', to='ticket.SessionInfo', verbose_name='场次'),
        ),
        migrations.AlterField(
            model_name='cysession',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CyShowEvent', verbose_name='关联节目'),
        ),
        migrations.AlterField(
            model_name='cyshowevent',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_show', to='ticket.ShowProject', verbose_name='节目'),
        ),
        migrations.AlterField(
            model_name='cyticketcode',
            name='cy_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caiyicloud.CyOrder', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='cyticketcode',
            name='ticket_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_code', to='ticket.TicketUserCode', verbose_name='演出票(座位)信息'),
        ),
        migrations.AlterField(
            model_name='cyvenue',
            name='venue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_venue', to='ticket.Venues', verbose_name='场馆'),
        ),
    ]
