# Generated by Django 3.0 on 2025-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0028_auto_20251110_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyorder',
            name='code_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '文本码'), (3, 'URL链接')], default=1, verbose_name='二维码类型'),
        ),
    ]
