# Generated by Django 3.0 on 2025-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0030_auto_20251231_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyorder',
            name='code_type',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '文本码'), (3, 'URL链接')], default=0, verbose_name='二维码类型'),
        ),
    ]
