# Generated by Django 3.0 on 2025-07-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='问题内容')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否使用')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='从小到大排列', verbose_name='排序')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '默认问题',
                'verbose_name_plural': '默认问题',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(verbose_name='最新提问时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话历史记录',
                'verbose_name_plural': '对话历史记录',
            },
        ),
        migrations.CreateModel(
            name='HistoryChatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000, verbose_name='提问')),
                ('answer', models.TextField(verbose_name='回答')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='提问时间')),
                ('answer_at', models.DateTimeField(blank=True, null=True, verbose_name='提问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_agent.HistoryChat', verbose_name='对话历史记录')),
            ],
            options={
                'verbose_name': '对话历史明细',
                'verbose_name_plural': '对话历史明细',
                'ordering': ['-pk'],
            },
        ),
    ]
