# Generated by Django 3.0 on 2025-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historychatdetail',
            old_name='user',
            new_name='hc',
        ),
        migrations.RemoveField(
            model_name='historychatdetail',
            name='answer_at',
        ),
        migrations.AlterField(
            model_name='historychat',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='最新提问时间'),
        ),
        migrations.AlterField(
            model_name='historychatdetail',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
