# Generated by Django 3.0 on 2025-08-02 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent', '0002_auto_20250729_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historychat',
            name='update_at',
        ),
        migrations.AddField(
            model_name='historychat',
            name='content',
            field=models.TextField(null=True, verbose_name='对话记录'),
        ),
        migrations.AddField(
            model_name='historychat',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='historychat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='HistoryChatDetail',
        ),
    ]
