# Generated by Django 3.0 on 2025-08-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_auto_20250802_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historychat',
            options={'ordering': ['-pk'], 'verbose_name': '对话历史记录', 'verbose_name_plural': '对话历史记录'},
        ),
    ]
