# Generated by Django 3.0 on 2025-08-19 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_auto_20250807_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='名称')),
                ('image', models.ImageField(upload_to='images/agent/img', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('code', models.PositiveSmallIntegerField(verbose_name='code')),
            ],
            options={
                'verbose_name': 'Ai智能体情绪动图',
                'verbose_name_plural': 'Ai智能体情绪动图',
            },
        ),
    ]
