# Generated by Django 3.0 on 2025-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_moodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodimage',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='code'),
        ),
    ]
