# Generated by Django 3.0 on 2025-08-19 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_auto_20250819_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='资源编号')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '图片资源',
                'verbose_name_plural': '图片资源',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImageResourceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/agent/res', validators=[django.core.validators.validate_image_file_extension], verbose_name='图片')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_agent.ImageResource', verbose_name='所属资源')),
            ],
            options={
                'verbose_name': '资源项',
                'verbose_name_plural': '资源项',
                'ordering': ['-pk'],
            },
        ),
    ]
