# Generated by Django 3.0 on 2025-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='dy_show_date',
            field=models.CharField(blank=True, help_text='抖音用例如2024-01-01至2024-06-30', max_length=100, null=True, verbose_name='本地演出日期'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='qualification_identity',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '主办方'), (2, '票务代理')], default=0, verbose_name='商家资质身份'),
        ),
    ]
