# Generated by Django 3.0 on 2025-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20250715_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='dc_expires_in',
            field=models.PositiveIntegerField(default=20, help_text='单位：分钟', verbose_name='动态码有效时间'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_dy_code',
            field=models.BooleanField(default=True, help_text='勾选后需要填写动态有效时间才能有效', verbose_name='是否动态码'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_theater_discount',
            field=models.BooleanField(default=False, verbose_name='是否参与剧场会员卡优惠'),
        ),
    ]
