# Generated by Django 3.0 on 2025-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20250715_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='title',
            field=models.CharField(help_text='100个字内', max_length=100, verbose_name='演出名称'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='演出名称'),
        ),
    ]
