# Generated by Django 3.0 on 2025-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20250715_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcolor',
            name='is_use',
            field=models.BooleanField(default=True, verbose_name='是否使用'),
        ),
    ]
