# Generated by Django 3.0 on 2025-07-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20250715_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveroomcpsitem',
            name='good',
            field=models.ForeignKey(help_text='仅支持上架且审核通过的正式品', limit_choices_to=models.Q(('push_status', 3), ('status', 1)), on_delete=django.db.models.deletion.CASCADE, to='ticket.SessionInfo', verbose_name='商品'),
        ),
    ]
