# Generated by Django 3.0 on 2025-07-18 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0002_cycategory_cygroupinfo_cyshowevent_cysupplierinfo'),
        ('ticket', '0006_auto_20250716_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showproject',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='showproject',
            name='cy_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='彩艺云ID'),
        ),
        migrations.AddField(
            model_name='showtype',
            name='cy_cate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_cate', to='caiyicloud.CyCategory', verbose_name='彩艺云类目'),
        ),
        migrations.AddField(
            model_name='venues',
            name='cy_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='彩艺云ID'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='host_approval_qual',
            field=models.ManyToManyField(blank=True, editable=False, help_text='主办方和票务代理,要传“营业性演出准予许可决定”5006', limit_choices_to=models.Q(qualification_type=5006), related_name='_showproject_host_approval_qual_+', to='ticket.TikTokQualRecord', verbose_name='营业性演出准予许可决定'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='logo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='images/ticket/shows', validators=[ticket.models.file_size, django.core.validators.validate_image_file_extension], verbose_name='宣传海报'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='other_notice',
            field=models.TextField(blank=True, editable=False, help_text='抖音商品使用', null=True, verbose_name='其他说明信息'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='qualification_identity',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '主办方'), (2, '票务代理')], default=0, editable=False, verbose_name='商家资质身份'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='ticket_agent_qual',
            field=models.ManyToManyField(blank=True, editable=False, help_text='票务代理,要传“演出主办方授权书” 5005', limit_choices_to=models.Q(qualification_type=5005), related_name='_showproject_ticket_agent_qual_+', to='ticket.TikTokQualRecord', verbose_name='演出主办方授权书'),
        ),
        migrations.AlterField(
            model_name='showtype',
            name='source_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '音乐'), (2, '戏剧'), (3, '曲艺'), (4, '舞蹈'), (5, '杂技'), (6, '展览'), (7, '赛事'), (8, '其他')], default=1, editable=False, null=True, verbose_name='演出行业标准分类'),
        ),
    ]
