# Generated by Django 3.0 on 2025-07-19 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
        ('ticket', '0007_auto_20250718_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninfo',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='sessioninfo',
            name='name_limit_num',
        ),
        migrations.RemoveField(
            model_name='sessioninfo',
            name='open_limit',
        ),
        migrations.RemoveField(
            model_name='showproject',
            name='buy_tips',
        ),
        migrations.RemoveField(
            model_name='showproject',
            name='cy_no',
        ),
        migrations.RemoveField(
            model_name='showproject',
            name='special_desc',
        ),
        migrations.RemoveField(
            model_name='venues',
            name='cy_no',
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='one_id_one_ticket',
            field=models.BooleanField(default=False, verbose_name='是否需要一票一证购买'),
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='showproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ticketfile',
            name='color_code',
            field=models.CharField(blank=True, editable=False, help_text='16进制色号', max_length=10, null=True, verbose_name='色号'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='display_order',
            field=models.IntegerField(default=0, editable=False, help_text='数字越大,商品越靠前', verbose_name='抖音商品排序'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='dy_sale_time',
            field=models.DateTimeField(blank=True, help_text='其他平台用', null=True, verbose_name='开售时间'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='dy_status',
            field=models.IntegerField(choices=[(1, '上架'), (2, '下架')], default=2, editable=False, verbose_name='抖音状态'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='fail_msg',
            field=models.TextField(blank=True, editable=False, max_length=1000, null=True, verbose_name='抖音错误信息'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_price',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已设价格'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='maizuo_data',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='麦座基础数据'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='mz_account',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.MaiZuoAccount', verbose_name='麦座账户'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='plan_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='通用计划ID'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='抖音商品ID'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='pull_mz_status',
            field=models.IntegerField(choices=[(1, '未拉取'), (2, '更新中'), (3, '已完成'), (4, '更新失败')], default=1, editable=False, verbose_name='麦座同步状态'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='push_status',
            field=models.IntegerField(choices=[(1, '未推送'), (4, '已推送'), (2, '审核中'), (3, '审核完成'), (5, '推送创建商品失败'), (6, '审核失败')], default=1, editable=False, verbose_name='推送抖音状态'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='tiktok_store',
            field=models.ForeignKey(blank=True, editable=False, help_text='推送商品到抖音必填', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.DouYinStore', verbose_name='抖音店铺'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='title',
            field=models.CharField(blank=True, help_text='60个字内,不填则默认项目名称，其他平台使用', max_length=60, null=True, verbose_name='场次名称'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='valid_start_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='抖音用：不填默认演出开始时间前2个小时', null=True, verbose_name='门票有效期开始时间'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='dy_pay_config',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.DouYinPayConfig', verbose_name='抖音支付商户'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='is_test',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否测试商品'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='origin_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13, verbose_name='抖音原价'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='tiktok_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/ticket/project', validators=[django.core.validators.validate_image_file_extension], verbose_name='抖音分享二维码'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketColor', verbose_name='票档颜色'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='is_ks',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否推送到快手'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='is_tiktok',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否推送到抖音'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='is_xhs',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否推送到小红书'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='plan_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='通用计划ID'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='抖音商品ID'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='push_xhs',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已经推送小红书'),
        ),
    ]
