# Generated by Django 3.0 on 2025-07-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20250719_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtype',
            name='category',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate', to='ticket.ShowTopCategory', verbose_name='抖音类目'),
        ),
    ]
