# Generated by Django 3.0 on 2025-07-24 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_auto_20250719_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessioninfo',
            options={'ordering': ['-start_at'], 'verbose_name': '场次', 'verbose_name_plural': '场次'},
        ),
        migrations.AlterModelOptions(
            name='sessionseat',
            options={'verbose_name': '场次座位', 'verbose_name_plural': '场次座位'},
        ),
        migrations.AlterModelOptions(
            name='showflag',
            options={'verbose_name': '节目标签', 'verbose_name_plural': '节目标签'},
        ),
        migrations.AlterModelOptions(
            name='showproject',
            options={'ordering': ['-pk'], 'verbose_name': '节目', 'verbose_name_plural': '节目'},
        ),
        migrations.AlterModelOptions(
            name='showsdetailimage',
            options={'verbose_name': '节目详情图', 'verbose_name_plural': '节目详情图'},
        ),
        migrations.AlterModelOptions(
            name='showtype',
            options={'ordering': ['-pk'], 'verbose_name': '节目分类', 'verbose_name_plural': '节目分类'},
        ),
        migrations.AlterModelOptions(
            name='venues',
            options={'ordering': ['display_order'], 'verbose_name': '场馆', 'verbose_name_plural': '场馆'},
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='name',
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowProject', verbose_name='节目'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='end_at',
            field=models.DateTimeField(db_index=True, verbose_name='场次结束时间'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_name_buy',
            field=models.BooleanField(default=False, help_text='0.01购票权限用户不走一单一证流程', verbose_name='是否一单一证'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='name_buy_num',
            field=models.PositiveIntegerField(default=0, help_text='用于限制一证最多购买多少张票，配合一单一证使用', verbose_name='单证限购数量'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='one_id_one_ticket',
            field=models.BooleanField(default=False, verbose_name='是否一票一证购买'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='order_limit_num',
            field=models.IntegerField(default=0, editable=False, help_text='购票限制,0表示不限购', verbose_name='每个订单限购数量'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='start_at',
            field=models.DateTimeField(db_index=True, verbose_name='场次开始时间'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='valid_start_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='抖音用：不填默认场次开始时间前2个小时', null=True, verbose_name='门票有效期开始时间'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='content',
            field=models.TextField(null=True, verbose_name='节目介绍'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='dy_show_date',
            field=models.CharField(blank=True, editable=False, help_text='抖音用例如2024-01-01至2024-06-30', max_length=100, null=True, verbose_name='本地演出日期'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='是否近期节目'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='show_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowType', verbose_name='节目类型'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='title',
            field=models.CharField(help_text='100个字内', max_length=100, verbose_name='节目名称'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='venues',
            field=models.ForeignKey(help_text='提交后不可修改', on_delete=django.db.models.deletion.CASCADE, to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='showsdetailimage',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowProject', verbose_name='节目'),
        ),
        migrations.AlterField(
            model_name='showtype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='节目名称'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='场次结束时间'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付'), (9, '剧场会员卡余额')], default=-1, verbose_name='付款类型'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='场次开场时间'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='title',
            field=models.CharField(max_length=60, verbose_name='节目名称'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='op_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_user', to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='source_type',
            field=models.IntegerField(choices=[(1, '微信退款'), (3, '剧场卡订单退款')], default=1, verbose_name='退款类型'),
        ),
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='status',
            field=models.IntegerField(choices=[(1, '待退款'), (2, '待第三方确认'), (3, '退款支付中'), (4, '退款支付失败'), (5, '已完成'), (6, '已取消')], default=1, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='TicketOrderRealName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_name_order', to='ticket.TicketOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单实名信息',
                'verbose_name_plural': '订单实名信息',
                'ordering': ['-pk'],
            },
        ),
    ]
