# Generated by Django 3.0 on 2025-07-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20250724_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_price',
            field=models.BooleanField(default=False, verbose_name='是否已设价格'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='show_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowType', verbose_name='节目分类'),
        ),
        migrations.CreateModel(
            name='ShowContentCategorySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='从小到大排序', verbose_name='排序')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowContentCategory', verbose_name='内容分类')),
                ('show_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowType', verbose_name='节目分类')),
            ],
            options={
                'verbose_name': '内容分类',
                'verbose_name_plural': '内容分类',
                'ordering': ['display_order'],
                'unique_together': {('cate', 'show_type')},
            },
        ),
    ]
