# Generated by Django 3.0 on 2025-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20250724_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcontentcategory',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='从小到大排序,首页展示前5项', verbose_name='排序'),
        ),
    ]
