# Generated by Django 3.0 on 2025-07-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_showcontentcategory_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcontentcategory',
            options={'ordering': ['display_order'], 'verbose_name': '内容分类', 'verbose_name_plural': '内容分类'},
        ),
    ]
