# Generated by Django 3.0 on 2025-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20250724_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='source_type',
            field=models.SmallIntegerField(choices=[(1, '自建'), (2, '彩艺云')], default=1, verbose_name='渠道类型'),
        ),
    ]
