# Generated by Django 3.0 on 2025-07-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_sessioninfo_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcontentcategorysecond',
            options={'ordering': ['display_order'], 'verbose_name': '二级分类', 'verbose_name_plural': '二级分类'},
        ),
        migrations.AlterField(
            model_name='showproject',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowContentCategory', verbose_name='内容分类'),
        ),
    ]
