# Generated by Django 3.0 on 2025-07-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20250728_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcontentcategory',
            options={'ordering': ['display_order'], 'verbose_name': '节目大类', 'verbose_name_plural': '节目大类'},
        ),
        migrations.AddField(
            model_name='showproject',
            name='cate_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowContentCategorySecond', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='showcontentcategorysecond',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowContentCategory', verbose_name='节目大类'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='cate',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowContentCategory', verbose_name='内容分类'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='show_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowType', verbose_name='节目分类'),
        ),
    ]
