# Generated by Django 3.0 on 2025-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20250728_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showuser',
            options={'ordering': ['-pk'], 'verbose_name': '常用观演人', 'verbose_name_plural': '常用观演人'},
        ),
        migrations.AddField(
            model_name='showcontentcategory',
            name='color_code',
            field=models.CharField(help_text='16进制色号', max_length=15, null=True, verbose_name='色号'),
        ),
        migrations.AlterField(
            model_name='showuser',
            name='id_card',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='身份证号'),
        ),
    ]
