# Generated by Django 3.0 on 2025-07-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20250729_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowContentCategory', verbose_name='内容分类'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='show_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ShowType', verbose_name='节目分类'),
        ),
    ]
