# Generated by Django 3.0 on 2025-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20250729_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcontentcategory',
            name='en_title',
            field=models.CharField(max_length=50, null=True, verbose_name='分类英文名称'),
        ),
    ]
