# Generated by Django 3.0 on 2025-07-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_showcontentcategory_en_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWatchingNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='从小到大排序', verbose_name='排序')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ticket.ShowProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '观演须知',
                'verbose_name_plural': '观演须知',
            },
        ),
        migrations.CreateModel(
            name='TicketPurchaseNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='从小到大排序', verbose_name='排序')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ticket.ShowProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '购票须知',
                'verbose_name_plural': '购票须知',
            },
        ),
    ]
