# Generated by Django 3.0 on 2025-07-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_ticketpurchasenotice_ticketwatchingnotices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketWatchingNotices',
            new_name='TicketWatchingNotice',
        ),
    ]
