# Generated by Django 3.0 on 2025-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_auto_20250729_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='notice',
            field=models.TextField(editable=False, null=True, verbose_name='购票须知'),
        ),
    ]
