# Generated by Django 3.0 on 2025-07-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiyicloud', '0009_auto_20250728_1135'),
        ('ticket', '0022_auto_20250729_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtype',
            name='cy_cate',
            field=models.OneToOneField(blank=True, help_text='彩艺云用才选', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cy_cate', to='caiyicloud.CyCategory', verbose_name='彩艺云类目'),
        ),
    ]
