# Generated by Django 3.0 on 2025-07-30 09:58

import common.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0023_auto_20250729_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='showuser',
            name='no',
            field=models.CharField(db_index=True, default=common.utils.get_no, max_length=64, null=True, unique=True, verbose_name='编号'),
        ),
        migrations.AlterUniqueTogether(
            name='showuser',
            unique_together={('user', 'name', 'id_card')},
        ),
        migrations.RemoveField(
            model_name='showuser',
            name='mobile',
        ),
    ]
