# Generated by Django 3.0 on 2025-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20250730_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='performer',
            field=models.ManyToManyField(blank=True, editable=False, to='ticket.ShowPerformer', verbose_name='演员'),
        ),
    ]
