# Generated by Django 3.0 on 2025-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_auto_20250730_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='channel_type',
            field=models.SmallIntegerField(choices=[(1, '自建'), (2, '彩艺云')], default=1, verbose_name='渠道类型'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信支付单号'),
        ),
    ]
