# Generated by Django 3.0 on 2025-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_auto_20250730_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='discount_type',
            field=models.IntegerField(choices=[(0, '无'), (1, '年度会员卡'), (2, '消费卷'), (3, '其他渠道')], default=0, verbose_name='优惠类型'),
        ),
    ]
