# Generated by Django 3.0 on 2025-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_auto_20250730_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='showuser',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
