# Generated by Django 3.0 on 2025-07-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_auto_20250731_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='discount_amount',
        ),
    ]
