# Generated by Django 3.0 on 2025-07-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_remove_ticketorder_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='cy_discount_overlay',
            field=models.BooleanField(default=False, verbose_name='是否开启彩艺云与本系统优惠叠加'),
        ),
        migrations.CreateModel(
            name='TicketOrderDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.IntegerField(choices=[(1, '年度会员卡'), (2, '消费卷'), (3, '彩艺套票优惠'), (4, '彩艺营销活动')], verbose_name='优惠类型')),
                ('title', models.CharField(max_length=20, verbose_name='优惠名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_order', to='ticket.TicketOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单优惠信息',
                'verbose_name_plural': '订单优惠信息',
                'ordering': ['-pk'],
            },
        ),
    ]
