# Generated by Django 3.0 on 2025-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_auto_20250731_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='discount_type',
        ),
    ]
