# Generated by Django 3.0 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_remove_ticketorder_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketusercode',
            name='source_type',
            field=models.IntegerField(choices=[(0, '无'), (1, '短视频'), (2, '直播间'), (3, '非cps订单')], default=0, editable=False, verbose_name='带货场景'),
        ),
        migrations.AlterField(
            model_name='ticketusercode',
            name='tiktok_check',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否推送抖音核销'),
        ),
    ]
