# Generated by Django 3.0 on 2025-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_auto_20250802_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketusercode',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='抖音商品ID'),
        ),
    ]
