# Generated by Django 3.0 on 2025-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_auto_20250802_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='theater_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='仅用剧场卡支付有效', max_digits=13, verbose_name='剧场卡订单退款数额'),
        ),
    ]
