# Generated by Django 3.0 on 2025-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_auto_20250807_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='dc_expires_in',
            field=models.PositiveIntegerField(default=30, help_text='单位：分钟', verbose_name='动态码有效时间'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_dy_code',
            field=models.BooleanField(default=False, help_text='勾选后需要填写动态有效时间才能有效,大于2小时才能分享核销码图片', verbose_name='是否动态码'),
        ),
    ]
