# Generated by Django 3.0 on 2025-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_auto_20250807_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcontentcategory',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
