# Generated by Django 3.0 on 2025-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_showcontentcategory_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='showproject',
            name='source_type',
            field=models.SmallIntegerField(choices=[(1, '自建'), (2, '彩艺云')], default=1, verbose_name='渠道类型'),
        ),
    ]
