# Generated by Django 3.0 on 2025-08-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_showproject_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='showtype',
            name='slug',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='标识'),
        ),
    ]
