# Generated by Django 3.0 on 2025-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_auto_20250820_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='content',
            field=models.TextField(null=True, verbose_name='演出介绍'),
        ),
    ]
