# Generated by Django 3.0 on 2025-08-21 16:53

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_auto_20250820_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='content',
            field=DjangoUeditor.models.UEditorField(null=True, verbose_name='节目介绍'),
        ),
    ]
