# Generated by Django 3.0 on 2025-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_auto_20250821_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_name_buy',
            field=models.BooleanField(default=False, verbose_name='是否一单一证'),
        ),
    ]
