# Generated by Django 3.0 on 2025-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_auto_20250822_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='is_theater_discount',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否参与剧场会员卡优惠'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='is_recommend',
            field=models.BooleanField(default=True, help_text='勾选后节目将会显示在首页底部【为你推荐】板块', verbose_name='为你推荐'),
        ),
    ]
