# Generated by Django 3.0 on 2025-09-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_auto_20250822_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='dy_sale_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='其他平台用', null=True, verbose_name='开售时间'),
        ),
    ]
