# Generated by Django 3.0 on 2025-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0046_auto_20250918_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='showproject',
            name='use_schedule',
            field=models.BooleanField(default=True, help_text='勾选后为日历样式', verbose_name='是否使用日历样式'),
        ),
    ]
