# Generated by Django 3.0 on 2025-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0047_showproject_use_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='can_check_at',
            field=models.DateTimeField(blank=True, help_text='自建场次用于限制开始可验票时间，不填为当天可验票', null=True, verbose_name='验票开始时间'),
        ),
    ]
