# Generated by Django 3.0 on 2025-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0048_sessioninfo_can_check_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproject',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='是否测试商品'),
        ),
    ]
