# Generated by Django 3.0 on 2025-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0049_auto_20250924_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfile',
            name='origin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='原价'),
        ),
    ]
