# Generated by Django 3.0 on 2025-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0050_auto_20250926_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(-1, '空'), (7, '微信小程序支付')], default=-1, verbose_name='付款类型'),
        ),
    ]
