# Generated by Django 3.0 on 2025-11-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_auto_20251031_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_info', to='ticket.ShowProject', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='cate_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowContentCategorySecond', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='show_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ShowType', verbose_name='节目分类'),
        ),
        migrations.AlterField(
            model_name='showproject',
            name='venues',
            field=models.ForeignKey(help_text='提交后不可修改', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.SessionInfo', verbose_name='场次'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Venues', verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='ticketusercode',
            name='session_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.SessionSeat', verbose_name='演出场次座位'),
        ),
    ]
