# Generated by Django 3.0 on 2025-11-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_auto_20251031_1734'),
        ('ticket', '0051_auto_20251031_1343'),
    ]

    operations = [
    ]
