# Generated by Django 3.0 on 2025-11-13 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0052_auto_20251110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionseat',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Seat', verbose_name='座位'),
        ),
        migrations.AlterField(
            model_name='sessionseat',
            name='ticket_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketFile', verbose_name='票档'),
        ),
        migrations.AlterField(
            model_name='ticketfile',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketColor', verbose_name='票档颜色'),
        ),
        migrations.AlterField(
            model_name='ticketgiverecord',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.SessionInfo', verbose_name='场次'),
        ),
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_refund_apply', to='ticket.TicketOrder', verbose_name='退款订单'),
        ),
        migrations.AlterField(
            model_name='ticketorderrefund',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
