# Generated by Django 3.0 on 2025-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0052_auto_20251110_1127'),
        ('ticket', '0053_auto_20251110_1124'),
    ]

    operations = [
    ]
