# Generated by Django 3.0 on 2025-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0053_auto_20251113_1134'),
        ('ticket', '0054_merge_20251110_1210'),
    ]

    operations = [
    ]
