"""
Django settings for lt_area project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from common.config import get_config
from celery.schedules import crontab
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '96_^%2*jid0&vt_^12&f98z7g()!d1fukk&!+8l$^_h4u&2kq6'
BASE_CONF = get_config()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = BASE_CONF.get('DEBUG', False)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'admins.apps.SortedAdminConfig',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'nested_admin',
    'rest_framework',
    'qcloud',
    'express',
    'mall',
    'shopping_points',
    'mp',
    'log',
    'renovation',
    'ticket',
    'kuaishou_wxa',
    'statistical',
    'xiaohongshu',
    'coupon',
    'home',
    'caiyicloud',
    # 'group_activity'
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    'dj_ext.middlewares.GlobalRequestMiddleware',
    'dj_ext.middlewares.AfterRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dj_ext.middlewares.ExceptionMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # 缓存地址
        "LOCATION": BASE_CONF['cache_config']['cache_redis'],
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # redis 这项没用
            'MAX_ENTRIES': 20000,
            # 使用线程池管理连接
            "CONNECTION_POOL_KWARGS": {"max_connections": BASE_CONF['cache_config']['max_connections']}
        }
    },
}

ROOT_URLCONF = 'dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ('*')
WSGI_APPLICATION = 'dj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
db_config = BASE_CONF['DATABASES']
DATABASES = db_config[db_config['use']]

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = '/static/'
# collectstatic task dir
STATIC_ROOT = BASE_CONF.get('static_root', os.path.join(BASE_DIR, 'static'))

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# for upload file storage dir
MEDIA_ROOT = BASE_CONF.get('media_root', os.path.join(BASE_DIR, 'media'))

# MEDIA_URL = BASE_CONF.get('media_url', '/media/')
MEDIA_URL = '/media/'
# for rest_framework

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'restframework_ext.permissions.RequestTokenSessionAuth',
        'restframework_ext.permissions.WeiXinLPAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ],
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',) + (
        ('rest_framework.renderers.BrowsableAPIRenderer',) if DEBUG else ()),
    'EXCEPTION_HANDLER': 'restframework_ext.exceptions.exception_handler'
}
# for simpleui
# SIMPLEUI_LOGIN_PARTICLES = False

# SIMPLEUI_HOME_ACTION = True
#
# SIMPLEUI_LOADING = False
#
AUTH_USER_MODEL = 'mall.User'

SIMPLEUI_HOME_INFO = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(name)s:%(levelname)s: %(asctime)s:%(process)d-%(thread)d: %(filename)s:%(lineno)d: %(module)s:%(funcName)s, %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        'biz': {
            'format': '%(levelname)s: %(asctime)s: %(message)s'
        },
        'trans': {
            'format': '%(levelname)s: %(message)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': [],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'fatal': {
            # log those fatal bug, which may have to fix by dev
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'fatal.log'),
            'formatter': 'verbose'
        },
        'trans': {
            # log those fatal bug, which may have to fix by dev
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'trans.log'),
            'formatter': 'trans'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'fatal'],
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'restframework_ext': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'mall': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'shopping_points': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'mp': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'express': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'renovation': {
            'handlers': ['console', 'fatal'],
            'level': 'WARNING',
        },
        'ticket': {
            'handlers': ['console', 'fatal'],
            'level': 'DEBUG',
        },
        # 'kuaishou_wxa': {
        #     'handlers': ['console', 'fatal'],
        #     'level': 'DEBUG',
        # },
        'statistical': {
            'handlers': ['console', 'fatal'],
            'level': 'DEBUG',
        },
        # 'xiaohongshu': {
        #     'handlers': ['console', 'fatal'],
        #     'level': 'DEBUG',
        # },
        'coupon': {
            'handlers': ['console', 'fatal'],
            'level': 'DEBUG',
        },
        'group_activity': {
            'handlers': ['console', 'fatal'],
            'level': 'DEBUG',
        },
        'caiyicloud': {
            'handlers': ['console', 'fatal'],
            'level': 'DEBUG',
        },
    }
}
TIME_INPUT_FORMATS = ['%H:%M:%S']
from mall.mall_conf import admin_url_site_name

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
SIMPLEUI_CONFIG = {
    # 开启系统默认菜单
    'system_keep': True,
    'dynamic': True,  # 每次都刷新菜单
    'hide_menu': ['票档']
    # 'menu_display': ['商城装修', '会员中心', '代理管理', '商城管理', '优惠券管理', '素材管理', '邮费模板管理', '日志管理', '基本配置']
    # 设置需要显示的菜单和排序
}
# 127.0.0.1 本地redis，使用redis的0号库来存
celery_config = get_config().get('celery')
CELERY_BROKER_URL = celery_config[
    'broker_url'] if celery_config else 'redis://127.0.0.1:6379/5'  # Broker配置，使用Redis作为消息中间件
# celery时区设置，建议与Django settings中TIME_ZONE同样时区，防止时差
CELERY_TIMEZONE = celery_config['TIMEZONE'] if celery_config else TIME_ZONE
# 1区用来存放任务状态和数据
CELERY_RESULT_BACKEND = celery_config[
    'result_backend'] if celery_config else 'redis://127.0.0.1:6379/6'  # BACKEND配置，这里使用redis
# celery内容等消息的格式设置，默认json
CELERY_ACCEPT_CONTENT = ['application/json', ]
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方案
CELERY_TASK_TIME_LIMIT = celery_config['TASK_TIME_LIMIT'] if celery_config else 15 * 60  # 任务超时时间
# 为存储结果设置过期日期，默认1天过期。如果beat开启，Celery每天会自动清除。
# 设为0，存储结果永不过期,单位秒
CELERY_RESULT_EXPIRES = celery_config['result_expires'] if celery_config else 3600
# 任务限流
CELERY_TASK_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_TASK_TRACK_STARTED = celery_config['TASK_TRACK_STARTED'] if celery_config else False
# # Worker并发数量，一般默认CPU核数，可以不设置
CELERY_WORKER_CONCURRENCY = celery_config['worker_concurrency'] if celery_config else 2
# 每个worker执行了多少任务就会死掉，默认是无限的
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200
# 设置定时和周期性任务
CELERY_BEAT_SCHEDULE = {
    # 麦座任务
    # 'auto_sync_mai_zuo': {
    #     'task': 'ticket.tasks.auto_sync_mai_zuo',
    #     'schedule': timedelta(seconds=91),  # 每隔10s执行一次（datetime的 timedelta方式来实现）
    #     # 'schedule': crontab(minute='*/2'),  # 每隔2分钟执行一次 （celery.schedule 的 crontab方式实现）
    # },
    # 'auto_mai_zuo_login': {
    #     'task': 'ticket.tasks.auto_mai_zuo_login',
    #     'schedule': timedelta(seconds=186),  # 每隔60s执行一次（datetime的 timedelta方式来实现）
    #     # 'schedule': crontab(minute='*/2'),  # 每隔2分钟执行一次 （celery.schedule 的 crontab方式实现）
    # },
    # 'auto_init_mai_zuo': {
    #     'task': 'ticket.tasks.auto_init_mai_zuo',
    #     'schedule': timedelta(seconds=125),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    #     # 'schedule': crontab(minute='*/2'),  # 每隔2分钟执行一次 （celery.schedule 的 crontab方式实现）
    # },

    # 其他任务
    'down_load_task': {
        'task': 'ticket.tasks.down_load_task',
        'schedule': timedelta(seconds=181),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'add_session_actual_amount': {
        'task': 'ticket.tasks.add_session_actual_amount',
        'schedule': timedelta(seconds=153),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'send_show_start_notice': {
        'task': 'ticket.tasks.send_show_start_notice',
        'schedule': timedelta(seconds=71),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'send_show_start_notice_give': {
        'task': 'ticket.tasks.send_show_start_notice_give',
        'schedule': timedelta(seconds=73),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'task_add_discount_total': {
        'task': 'mall.tasks.task_add_discount_total',
        'schedule': timedelta(seconds=123),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'update_ticket_file_stock_from_redis': {
        'task': 'ticket.tasks.update_ticket_file_stock_from_redis',
        'schedule': timedelta(seconds=33),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'settle_order_award_task': {
        'task': 'ticket.tasks.settle_order_award_task',
        'schedule': timedelta(seconds=73)
    },
    'update_stl_redis': {
        'task': 'statistical.tasks.update_stl_redis',
        'schedule': timedelta(seconds=130),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'update_stl_total_redis': {
        'task': 'statistical.tasks.update_stl_total_redis',
        'schedule': timedelta(seconds=130),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'task_add_session_agent_day_sum': {
        'task': 'statistical.tasks.task_add_session_agent_day_sum',
        'schedule': timedelta(seconds=135),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'task_add_session_cps_day_sum': {
        'task': 'statistical.tasks.task_add_session_cps_day_sum',
        'schedule': timedelta(seconds=135),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'ticket_order_expire': {
        'task': 'ticket.tasks.ticket_order_expire',
        'schedule': timedelta(seconds=60),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'auth_check_over_time_code': {
        'task': 'ticket.tasks.auth_check_over_time_code',
        'schedule': timedelta(seconds=60),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'update_goods_sales': {
        'task': 'ticket.tasks.update_goods_sales',
        'schedule': timedelta(seconds=60),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'update_focus_num': {
        'task': 'ticket.tasks.update_focus_num',
        'schedule': timedelta(seconds=155),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },

    'show_expire_off': {
        'task': 'ticket.tasks.show_expire_off',
        'schedule': timedelta(seconds=60),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'task_add_commission_balance': {
        'task': 'ticket.tasks.task_add_commission_balance',
        'schedule': timedelta(seconds=75),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },
    'coupon_expire_task': {
        'task': 'coupon.tasks.coupon_expire_task',
        'schedule': timedelta(seconds=61),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    },

    # 快手任务
    # 'session_push_to_ks': {
    #     'task': 'kuaishou_wxa.tasks.session_push_to_ks',
    #     'schedule': timedelta(seconds=81),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'settle_order_to_ks': {
    #     'task': 'kuaishou_wxa.tasks.settle_order_to_ks',
    #     'schedule': timedelta(seconds=307),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'ks_order_report_task': {
    #     'task': 'kuaishou_wxa.tasks.ks_order_report_task',
    #     'schedule': timedelta(seconds=91),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'ks_check_cps': {
    #     'task': 'kuaishou_wxa.tasks.ks_check_cps',
    #     'schedule': timedelta(seconds=900),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },

    # 抖音任务
    # 'check_add_booking_task': {
    #     'task': 'ticket.tasks.check_add_booking_task',
    #     'schedule': crontab(minute=00, hour=1)
    # },
    # 'session_push_to_xhs_task': {
    #     'task': 'xiaohongshu.tasks.session_push_to_xhs',
    #     'schedule': timedelta(seconds=67)
    # },
    # 'goods_push_to_dou_yin': {
    #     'task': 'ticket.tasks.goods_push_to_dou_yin',
    #     'schedule': timedelta(seconds=310),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'goods_draft_dou_yin': {
    #     'task': 'ticket.tasks.goods_draft_dou_yin',
    #     'schedule': timedelta(seconds=150),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'auth_check_over_time_code_tiktok': {
    #     'task': 'ticket.tasks.auth_check_over_time_code_tiktok',
    #     'schedule': timedelta(seconds=60),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'plan_to_dou_yin': {
    #     'task': 'ticket.tasks.plan_to_dou_yin',
    #     'schedule': timedelta(seconds=155),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'check_cps_source': {
    #     'task': 'ticket.tasks.check_cps_source',
    #     'schedule': timedelta(seconds=605),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },
    # 'pull_tiktok_qual': {
    #     'task': 'ticket.tasks.pull_tiktok_qual',
    #     'schedule': timedelta(hours=12),  # 每隔10分钟执行一次（datetime的 timedelta方式来实现）
    # },

    # 小红书任务
    # 'xhs_auto_verify_code_task': {
    #     'task': 'xiaohongshu.tasks.xhs_auto_verify_code',
    #     'schedule': timedelta(seconds=63)
    # },
    # 'xhs_check_approve_task': {
    #     'task': 'xiaohongshu.tasks.xhs_check_approve_task',
    #     'schedule': timedelta(seconds=125)
    # },
    # 'xhs_get_poi_list': {
    #     'task': 'ticket.tasks.xhs_get_poi_list',
    #     'schedule': crontab(minute=30, hour=0)
    # },

}
